DROP TABLE IF EXISTS t;
CREATE TABLE t (
id int4 PRIMARY KEY,
x_bool bool, -- b, B, -, pg_catalog
x_bytea bytea, -- b, U, -, pg_catalog
x_char char, -- b, Z, -, pg_catalog
x_name name, -- b, S, raw_array_subscript_handler, pg_catalog
x_int8 int8, -- b, N, -, pg_catalog
x_int2 int2, -- b, N, -, pg_catalog
x_int2vector int2vector, -- b, A, array_subscript_handler, pg_catalog
x_int4 int4, -- b, N, -, pg_catalog
x_regproc regproc, -- b, N, -, pg_catalog
x_text text, -- b, S, -, pg_catalog
x_oid oid, -- b, N, -, pg_catalog
x_tid tid, -- b, U, -, pg_catalog
x_xid xid, -- b, U, -, pg_catalog
x_cid cid, -- b, U, -, pg_catalog
x_oidvector oidvector, -- b, A, array_subscript_handler, pg_catalog
x_pg_type pg_type, -- c, C, -, pg_catalog
--x_pg_attribute pg_attribute, -- c, C, -, pg_catalog                         ERROR: SQL Error [42P16]: ERROR: column "attmissingval" has pseudo-type anyarray
x_pg_proc pg_proc, -- c, C, -, pg_catalog
x_pg_class pg_class, -- c, C, -, pg_catalog
x_json json, -- b, U, -, pg_catalog
x_xml xml, -- b, U, -, pg_catalog
x_pg_node_tree pg_node_tree, -- b, Z, -, pg_catalog


x_pg_ndistinct pg_ndistinct, -- b, Z, -, pg_catalog
x_pg_dependencies pg_dependencies, -- b, Z, -, pg_catalog
x_pg_mcv_list pg_mcv_list, -- b, Z, -, pg_catalog
--x_pg_ddl_command pg_ddl_command, -- p, P, -, pg_catalog                ERROR: SQL Error [42P16]: ERROR: column "x_pg_ddl_command" has pseudo-type pg_ddl_command
x_xid8 xid8, -- b, U, -, pg_catalog
x_point point, -- b, G, raw_array_subscript_handler, pg_catalog
x_lseg lseg, -- b, G, raw_array_subscript_handler, pg_catalog
x_path path, -- b, G, -, pg_catalog
x_box box, -- b, G, raw_array_subscript_handler, pg_catalog
x_polygon polygon, -- b, G, -, pg_catalog
x_line line, -- b, G, raw_array_subscript_handler, pg_catalog
x_float4 float4, -- b, N, -, pg_catalog
x_float8 float8, -- b, N, -, pg_catalog
--x_unknown unknown, -- p, X, -, pg_catalog
x_circle circle, -- b, G, -, pg_catalog
x_money money, -- b, N, -, pg_catalog
x_macaddr macaddr, -- b, U, -, pg_catalog
x_inet inet, -- b, I, -, pg_catalog
x_cidr cidr, -- b, I, -, pg_catalog
x_macaddr8 macaddr8, -- b, U, -, pg_catalog
x_aclitem aclitem, -- b, U, -, pg_catalog
x_bpchar bpchar, -- b, S, -, pg_catalog
x_varchar varchar, -- b, S, -, pg_catalog
x_date date, -- b, D, -, pg_catalog
x_time time, -- b, D, -, pg_catalog
x_timestamp timestamp, -- b, D, -, pg_catalog
x_timestamptz timestamptz, -- b, D, -, pg_catalog
x_interval interval, -- b, T, -, pg_catalog
x_timetz timetz, -- b, D, -, pg_catalog
x_bit bit, -- b, V, -, pg_catalog
x_varbit varbit, -- b, V, -, pg_catalog
x_numeric numeric, -- b, N, -, pg_catalog
x_refcursor refcursor, -- b, U, -, pg_catalog
x_regprocedure regprocedure, -- b, N, -, pg_catalog


x_regoper regoper, -- b, N, -, pg_catalog
x_regoperator regoperator, -- b, N, -, pg_catalog
x_regclass regclass, -- b, N, -, pg_catalog
x_regcollation regcollation, -- b, N, -, pg_catalog
x_regtype regtype, -- b, N, -, pg_catalog
x_regrole regrole, -- b, N, -, pg_catalog
x_regnamespace regnamespace, -- b, N, -, pg_catalog
x_uuid uuid, -- b, U, -, pg_catalog
x_pg_lsn pg_lsn, -- b, U, -, pg_catalog
x_tsvector tsvector, -- b, U, -, pg_catalog
x_gtsvector gtsvector, -- b, U, -, pg_catalog
x_tsquery tsquery, -- b, U, -, pg_catalog
x_regconfig regconfig, -- b, N, -, pg_catalog
x_regdictionary regdictionary, -- b, N, -, pg_catalog
x_jsonb jsonb, -- b, U, jsonb_subscript_handler, pg_catalog
x_jsonpath jsonpath, -- b, U, -, pg_catalog


x_txid_snapshot txid_snapshot, -- b, U, -, pg_catalog
x_pg_snapshot pg_snapshot, -- b, U, -, pg_catalog
x_int4range int4range, -- r, R, -, pg_catalog
x_numrange numrange, -- r, R, -, pg_catalog
x_tsrange tsrange, -- r, R, -, pg_catalog
x_tstzrange tstzrange, -- r, R, -, pg_catalog
x_daterange daterange, -- r, R, -, pg_catalog
x_int8range int8range, -- r, R, -, pg_catalog
x_int4multirange int4multirange, -- m, R, -, pg_catalog
x_nummultirange nummultirange, -- m, R, -, pg_catalog
x_tsmultirange tsmultirange, -- m, R, -, pg_catalog
x_tstzmultirange tstzmultirange, -- m, R, -, pg_catalog
x_datemultirange datemultirange, -- m, R, -, pg_catalog
x_int8multirange int8multirange, -- m, R, -, pg_catalog
--x_record record, -- p, P, -, pg_catalog
--x__record _record, -- p, P, array_subscript_handler, pg_catalog
--x_cstring cstring, -- p, P, -, pg_catalog
--x_anyarray anyarray, -- p, P, -, pg_catalog
--x_void void, -- p, P, -, pg_catalog
--x_trigger trigger, -- p, P, -, pg_catalog
--x_event_trigger event_trigger, -- p, P, -, pg_catalog
--x_language_handler language_handler, -- p, P, -, pg_catalog
--x_internal internal, -- p, P, -, pg_catalog
--x_anyelement anyelement, -- p, P, -, pg_catalog
--x_anynonarray anynonarray, -- p, P, -, pg_catalog
--x_anyenum anyenum, -- p, P, -, pg_catalog
--x_fdw_handler fdw_handler, -- p, P, -, pg_catalog
--x_index_am_handler index_am_handler, -- p, P, -, pg_catalog
--x_tsm_handler tsm_handler, -- p, P, -, pg_catalog
--x_table_am_handler table_am_handler, -- p, P, -, pg_catalog
--x_anyrange anyrange, -- p, P, -, pg_catalog
--x_anycompatible anycompatible, -- p, P, -, pg_catalog
--x_anycompatiblearray anycompatiblearray, -- p, P, -, pg_catalog
--x_anycompatiblenonarray anycompatiblenonarray, -- p, P, -, pg_catalog
--x_anycompatiblerange anycompatiblerange, -- p, P, -, pg_catalog
--x_anymultirange anymultirange, -- p, P, -, pg_catalog
--x_anycompatiblemultirange anycompatiblemultirange, -- p, P, -, pg_catalog
--x_pg_brin_bloom_summary pg_brin_bloom_summary, -- b, Z, -, pg_catalog
--x_pg_brin_minmax_multi_summary pg_brin_minmax_multi_summary, -- b, Z, -, pg_catalog
x__bool _bool, -- b, A, array_subscript_handler, pg_catalog
x__bytea _bytea, -- b, A, array_subscript_handler, pg_catalog
x__char _char, -- b, A, array_subscript_handler, pg_catalog
x__name _name, -- b, A, array_subscript_handler, pg_catalog
x__int8 _int8, -- b, A, array_subscript_handler, pg_catalog
x__int2 _int2, -- b, A, array_subscript_handler, pg_catalog
x__int2vector _int2vector, -- b, A, array_subscript_handler, pg_catalog
x__int4 _int4, -- b, A, array_subscript_handler, pg_catalog
x__regproc _regproc, -- b, A, array_subscript_handler, pg_catalog
x__text _text, -- b, A, array_subscript_handler, pg_catalog
x__oid _oid, -- b, A, array_subscript_handler, pg_catalog
x__tid _tid, -- b, A, array_subscript_handler, pg_catalog
x__xid _xid, -- b, A, array_subscript_handler, pg_catalog
x__cid _cid, -- b, A, array_subscript_handler, pg_catalog
x__oidvector _oidvector, -- b, A, array_subscript_handler, pg_catalog
x__pg_type _pg_type, -- b, A, array_subscript_handler, pg_catalog
--x__pg_attribute _pg_attribute, -- b, A, array_subscript_handler, pg_catalog


x__pg_proc _pg_proc, -- b, A, array_subscript_handler, pg_catalog
x__pg_class _pg_class, -- b, A, array_subscript_handler, pg_catalog
x__json _json, -- b, A, array_subscript_handler, pg_catalog
x__xml _xml, -- b, A, array_subscript_handler, pg_catalog
x__xid8 _xid8, -- b, A, array_subscript_handler, pg_catalog
x__point _point, -- b, A, array_subscript_handler, pg_catalog
x__lseg _lseg, -- b, A, array_subscript_handler, pg_catalog
x__path _path, -- b, A, array_subscript_handler, pg_catalog
x__box _box, -- b, A, array_subscript_handler, pg_catalog
x__polygon _polygon, -- b, A, array_subscript_handler, pg_catalog
x__line _line, -- b, A, array_subscript_handler, pg_catalog
x__float4 _float4, -- b, A, array_subscript_handler, pg_catalog
x__float8 _float8, -- b, A, array_subscript_handler, pg_catalog
x__circle _circle, -- b, A, array_subscript_handler, pg_catalog
x__money _money, -- b, A, array_subscript_handler, pg_catalog
x__macaddr _macaddr, -- b, A, array_subscript_handler, pg_catalog
x__inet _inet, -- b, A, array_subscript_handler, pg_catalog
x__cidr _cidr, -- b, A, array_subscript_handler, pg_catalog
x__macaddr8 _macaddr8, -- b, A, array_subscript_handler, pg_catalog
x__aclitem _aclitem, -- b, A, array_subscript_handler, pg_catalog
x__bpchar _bpchar, -- b, A, array_subscript_handler, pg_catalog
x__varchar _varchar, -- b, A, array_subscript_handler, pg_catalog
x__date _date, -- b, A, array_subscript_handler, pg_catalog
x__time _time, -- b, A, array_subscript_handler, pg_catalog
x__timestamp _timestamp, -- b, A, array_subscript_handler, pg_catalog
x__timestamptz _timestamptz, -- b, A, array_subscript_handler, pg_catalog
x__interval _interval, -- b, A, array_subscript_handler, pg_catalog
x__timetz _timetz, -- b, A, array_subscript_handler, pg_catalog
x__bit _bit, -- b, A, array_subscript_handler, pg_catalog
x__varbit _varbit, -- b, A, array_subscript_handler, pg_catalog
x__numeric _numeric, -- b, A, array_subscript_handler, pg_catalog
x__refcursor _refcursor, -- b, A, array_subscript_handler, pg_catalog
x__regprocedure _regprocedure, -- b, A, array_subscript_handler, pg_catalog
x__regoper _regoper, -- b, A, array_subscript_handler, pg_catalog
x__regoperator _regoperator, -- b, A, array_subscript_handler, pg_catalog
x__regclass _regclass, -- b, A, array_subscript_handler, pg_catalog
x__regcollation _regcollation, -- b, A, array_subscript_handler, pg_catalog
x__regtype _regtype, -- b, A, array_subscript_handler, pg_catalog
x__regrole _regrole, -- b, A, array_subscript_handler, pg_catalog
x__regnamespace _regnamespace, -- b, A, array_subscript_handler, pg_catalog
x__uuid _uuid, -- b, A, array_subscript_handler, pg_catalog
x__pg_lsn _pg_lsn, -- b, A, array_subscript_handler, pg_catalog
x__tsvector _tsvector, -- b, A, array_subscript_handler, pg_catalog
x__gtsvector _gtsvector, -- b, A, array_subscript_handler, pg_catalog
x__tsquery _tsquery, -- b, A, array_subscript_handler, pg_catalog
x__regconfig _regconfig, -- b, A, array_subscript_handler, pg_catalog
x__regdictionary _regdictionary, -- b, A, array_subscript_handler, pg_catalog
x__jsonb _jsonb, -- b, A, array_subscript_handler, pg_catalog
x__jsonpath _jsonpath, -- b, A, array_subscript_handler, pg_catalog
x__txid_snapshot _txid_snapshot, -- b, A, array_subscript_handler, pg_catalog
x__pg_snapshot _pg_snapshot, -- b, A, array_subscript_handler, pg_catalog
x__int4range _int4range, -- b, A, array_subscript_handler, pg_catalog
x__numrange _numrange, -- b, A, array_subscript_handler, pg_catalog
x__tsrange _tsrange, -- b, A, array_subscript_handler, pg_catalog
x__tstzrange _tstzrange, -- b, A, array_subscript_handler, pg_catalog
x__daterange _daterange, -- b, A, array_subscript_handler, pg_catalog
x__int8range _int8range, -- b, A, array_subscript_handler, pg_catalog
x__int4multirange _int4multirange, -- b, A, array_subscript_handler, pg_catalog
x__nummultirange _nummultirange, -- b, A, array_subscript_handler, pg_catalog
x__tsmultirange _tsmultirange, -- b, A, array_subscript_handler, pg_catalog
x__tstzmultirange _tstzmultirange, -- b, A, array_subscript_handler, pg_catalog
x__datemultirange _datemultirange, -- b, A, array_subscript_handler, pg_catalog
x__int8multirange _int8multirange, -- b, A, array_subscript_handler, pg_catalog
--x__cstring _cstring, -- b, A, array_subscript_handler, pg_catalog

x_pg_attrdef pg_attrdef, -- c, C, -, pg_catalog
x__pg_attrdef _pg_attrdef, -- b, A, array_subscript_handler, pg_catalog
x_pg_constraint pg_constraint, -- c, C, -, pg_catalog
x__pg_constraint _pg_constraint, -- b, A, array_subscript_handler, pg_catalog
x_pg_inherits pg_inherits, -- c, C, -, pg_catalog
x__pg_inherits _pg_inherits, -- b, A, array_subscript_handler, pg_catalog
x_pg_index pg_index, -- c, C, -, pg_catalog
x__pg_index _pg_index, -- b, A, array_subscript_handler, pg_catalog
x_pg_operator pg_operator, -- c, C, -, pg_catalog
x__pg_operator _pg_operator, -- b, A, array_subscript_handler, pg_catalog
x_pg_opfamily pg_opfamily, -- c, C, -, pg_catalog
x__pg_opfamily _pg_opfamily, -- b, A, array_subscript_handler, pg_catalog
x_pg_opclass pg_opclass, -- c, C, -, pg_catalog
x__pg_opclass _pg_opclass, -- b, A, array_subscript_handler, pg_catalog
x_pg_am pg_am, -- c, C, -, pg_catalog
x__pg_am _pg_am, -- b, A, array_subscript_handler, pg_catalog
x_pg_amop pg_amop, -- c, C, -, pg_catalog
x__pg_amop _pg_amop, -- b, A, array_subscript_handler, pg_catalog
x_pg_amproc pg_amproc, -- c, C, -, pg_catalog
x__pg_amproc _pg_amproc, -- b, A, array_subscript_handler, pg_catalog
x_pg_language pg_language, -- c, C, -, pg_catalog
x__pg_language _pg_language, -- b, A, array_subscript_handler, pg_catalog
x_pg_largeobject_metadata pg_largeobject_metadata, -- c, C, -, pg_catalog
x__pg_largeobject_metadata _pg_largeobject_metadata, -- b, A, array_subscript_handler, pg_catalog
x_pg_largeobject pg_largeobject, -- c, C, -, pg_catalog
x__pg_largeobject _pg_largeobject, -- b, A, array_subscript_handler, pg_catalog
x_pg_aggregate pg_aggregate, -- c, C, -, pg_catalog
x__pg_aggregate _pg_aggregate, -- b, A, array_subscript_handler, pg_catalog
--x_pg_statistic pg_statistic, -- c, C, -, pg_catalog
--x__pg_statistic _pg_statistic, -- b, A, array_subscript_handler, pg_catalog
--x_pg_statistic_ext pg_statistic_ext, -- c, C, -, pg_catalog
--x__pg_statistic_ext _pg_statistic_ext, -- b, A, array_subscript_handler, pg_catalog
--x_pg_statistic_ext_data pg_statistic_ext_data, -- c, C, -, pg_catalog
--x__pg_statistic_ext_data _pg_statistic_ext_data, -- b, A, array_subscript_handler, pg_catalog
x_pg_rewrite pg_rewrite, -- c, C, -, pg_catalog
x__pg_rewrite _pg_rewrite, -- b, A, array_subscript_handler, pg_catalog
x_pg_trigger pg_trigger, -- c, C, -, pg_catalog
x__pg_trigger _pg_trigger, -- b, A, array_subscript_handler, pg_catalog
x_pg_event_trigger pg_event_trigger, -- c, C, -, pg_catalog
x__pg_event_trigger _pg_event_trigger, -- b, A, array_subscript_handler, pg_catalog
x_pg_description pg_description, -- c, C, -, pg_catalog
x__pg_description _pg_description, -- b, A, array_subscript_handler, pg_catalog
x_pg_cast pg_cast, -- c, C, -, pg_catalog
x__pg_cast _pg_cast, -- b, A, array_subscript_handler, pg_catalog
x_pg_enum pg_enum, -- c, C, -, pg_catalog
x__pg_enum _pg_enum, -- b, A, array_subscript_handler, pg_catalog
x_pg_namespace pg_namespace, -- c, C, -, pg_catalog
x__pg_namespace _pg_namespace, -- b, A, array_subscript_handler, pg_catalog
x_pg_conversion pg_conversion, -- c, C, -, pg_catalog
x__pg_conversion _pg_conversion, -- b, A, array_subscript_handler, pg_catalog
x_pg_depend pg_depend, -- c, C, -, pg_catalog
x__pg_depend _pg_depend, -- b, A, array_subscript_handler, pg_catalog
x_pg_database pg_database, -- c, C, -, pg_catalog
x__pg_database _pg_database, -- b, A, array_subscript_handler, pg_catalog
x_pg_db_role_setting pg_db_role_setting, -- c, C, -, pg_catalog
x__pg_db_role_setting _pg_db_role_setting, -- b, A, array_subscript_handler, pg_catalog
x_pg_tablespace pg_tablespace, -- c, C, -, pg_catalog
x__pg_tablespace _pg_tablespace, -- b, A, array_subscript_handler, pg_catalog
x_pg_authid pg_authid, -- c, C, -, pg_catalog
x__pg_authid _pg_authid, -- b, A, array_subscript_handler, pg_catalog
x_pg_auth_members pg_auth_members, -- c, C, -, pg_catalog
x__pg_auth_members _pg_auth_members, -- b, A, array_subscript_handler, pg_catalog
x_pg_shdepend pg_shdepend, -- c, C, -, pg_catalog
x__pg_shdepend _pg_shdepend, -- b, A, array_subscript_handler, pg_catalog
x_pg_shdescription pg_shdescription, -- c, C, -, pg_catalog
x__pg_shdescription _pg_shdescription, -- b, A, array_subscript_handler, pg_catalog
x_pg_ts_config pg_ts_config, -- c, C, -, pg_catalog
x__pg_ts_config _pg_ts_config, -- b, A, array_subscript_handler, pg_catalog
x_pg_ts_config_map pg_ts_config_map, -- c, C, -, pg_catalog
x__pg_ts_config_map _pg_ts_config_map, -- b, A, array_subscript_handler, pg_catalog
x_pg_ts_dict pg_ts_dict, -- c, C, -, pg_catalog
x__pg_ts_dict _pg_ts_dict, -- b, A, array_subscript_handler, pg_catalog
x_pg_ts_parser pg_ts_parser, -- c, C, -, pg_catalog
x__pg_ts_parser _pg_ts_parser, -- b, A, array_subscript_handler, pg_catalog
x_pg_ts_template pg_ts_template, -- c, C, -, pg_catalog
x__pg_ts_template _pg_ts_template, -- b, A, array_subscript_handler, pg_catalog
x_pg_extension pg_extension, -- c, C, -, pg_catalog
x__pg_extension _pg_extension, -- b, A, array_subscript_handler, pg_catalog
x_pg_foreign_data_wrapper pg_foreign_data_wrapper, -- c, C, -, pg_catalog
x__pg_foreign_data_wrapper _pg_foreign_data_wrapper, -- b, A, array_subscript_handler, pg_catalog
x_pg_foreign_server pg_foreign_server, -- c, C, -, pg_catalog
x__pg_foreign_server _pg_foreign_server, -- b, A, array_subscript_handler, pg_catalog
x_pg_user_mapping pg_user_mapping, -- c, C, -, pg_catalog
x__pg_user_mapping _pg_user_mapping, -- b, A, array_subscript_handler, pg_catalog
x_pg_foreign_table pg_foreign_table, -- c, C, -, pg_catalog
x__pg_foreign_table _pg_foreign_table, -- b, A, array_subscript_handler, pg_catalog
x_pg_policy pg_policy, -- c, C, -, pg_catalog
x__pg_policy _pg_policy, -- b, A, array_subscript_handler, pg_catalog
x_pg_replication_origin pg_replication_origin, -- c, C, -, pg_catalog
x__pg_replication_origin _pg_replication_origin, -- b, A, array_subscript_handler, pg_catalog
x_pg_default_acl pg_default_acl, -- c, C, -, pg_catalog
x__pg_default_acl _pg_default_acl, -- b, A, array_subscript_handler, pg_catalog
x_pg_init_privs pg_init_privs, -- c, C, -, pg_catalog
x__pg_init_privs _pg_init_privs, -- b, A, array_subscript_handler, pg_catalog
x_pg_seclabel pg_seclabel, -- c, C, -, pg_catalog
x__pg_seclabel _pg_seclabel, -- b, A, array_subscript_handler, pg_catalog
x_pg_shseclabel pg_shseclabel, -- c, C, -, pg_catalog
x__pg_shseclabel _pg_shseclabel, -- b, A, array_subscript_handler, pg_catalog
x_pg_collation pg_collation, -- c, C, -, pg_catalog
x__pg_collation _pg_collation, -- b, A, array_subscript_handler, pg_catalog
x_pg_parameter_acl pg_parameter_acl, -- c, C, -, pg_catalog
x__pg_parameter_acl _pg_parameter_acl, -- b, A, array_subscript_handler, pg_catalog
x_pg_partitioned_table pg_partitioned_table, -- c, C, -, pg_catalog
x__pg_partitioned_table _pg_partitioned_table, -- b, A, array_subscript_handler, pg_catalog
x_pg_range pg_range, -- c, C, -, pg_catalog
x__pg_range _pg_range, -- b, A, array_subscript_handler, pg_catalog
x_pg_transform pg_transform, -- c, C, -, pg_catalog
x__pg_transform _pg_transform, -- b, A, array_subscript_handler, pg_catalog
x_pg_sequence pg_sequence, -- c, C, -, pg_catalog
x__pg_sequence _pg_sequence, -- b, A, array_subscript_handler, pg_catalog
x_pg_publication pg_publication, -- c, C, -, pg_catalog
x__pg_publication _pg_publication, -- b, A, array_subscript_handler, pg_catalog
x_pg_publication_namespace pg_publication_namespace, -- c, C, -, pg_catalog
x__pg_publication_namespace _pg_publication_namespace, -- b, A, array_subscript_handler, pg_catalog
x_pg_publication_rel pg_publication_rel, -- c, C, -, pg_catalog
x__pg_publication_rel _pg_publication_rel, -- b, A, array_subscript_handler, pg_catalog
x_pg_subscription pg_subscription, -- c, C, -, pg_catalog
x__pg_subscription _pg_subscription, -- b, A, array_subscript_handler, pg_catalog
x_pg_subscription_rel pg_subscription_rel, -- c, C, -, pg_catalog
x__pg_subscription_rel _pg_subscription_rel, -- b, A, array_subscript_handler, pg_catalog
x_pg_roles pg_roles, -- c, C, -, pg_catalog
x__pg_roles _pg_roles, -- b, A, array_subscript_handler, pg_catalog
x_pg_shadow pg_shadow, -- c, C, -, pg_catalog
x__pg_shadow _pg_shadow, -- b, A, array_subscript_handler, pg_catalog
x_pg_group pg_group, -- c, C, -, pg_catalog
x__pg_group _pg_group, -- b, A, array_subscript_handler, pg_catalog
x_pg_user pg_user, -- c, C, -, pg_catalog
x__pg_user _pg_user, -- b, A, array_subscript_handler, pg_catalog
x_pg_policies pg_policies, -- c, C, -, pg_catalog
x__pg_policies _pg_policies, -- b, A, array_subscript_handler, pg_catalog
x_pg_rules pg_rules, -- c, C, -, pg_catalog
x__pg_rules _pg_rules, -- b, A, array_subscript_handler, pg_catalog
x_pg_views pg_views, -- c, C, -, pg_catalog
x__pg_views _pg_views, -- b, A, array_subscript_handler, pg_catalog
x_pg_tables pg_tables, -- c, C, -, pg_catalog
x__pg_tables _pg_tables, -- b, A, array_subscript_handler, pg_catalog
x_pg_matviews pg_matviews, -- c, C, -, pg_catalog
x__pg_matviews _pg_matviews, -- b, A, array_subscript_handler, pg_catalog
x_pg_indexes pg_indexes, -- c, C, -, pg_catalog
x__pg_indexes _pg_indexes, -- b, A, array_subscript_handler, pg_catalog
x_pg_sequences pg_sequences, -- c, C, -, pg_catalog
x__pg_sequences _pg_sequences, -- b, A, array_subscript_handler, pg_catalog
--x_pg_stats pg_stats, -- c, C, -, pg_catalog
--x__pg_stats _pg_stats, -- b, A, array_subscript_handler, pg_catalog
--x_pg_stats_ext pg_stats_ext, -- c, C, -, pg_catalog
--x__pg_stats_ext _pg_stats_ext, -- b, A, array_subscript_handler, pg_catalog
--x_pg_stats_ext_exprs pg_stats_ext_exprs, -- c, C, -, pg_catalog
--x__pg_stats_ext_exprs _pg_stats_ext_exprs, -- b, A, array_subscript_handler, pg_catalog
x_pg_publication_tables pg_publication_tables, -- c, C, -, pg_catalog
x__pg_publication_tables _pg_publication_tables, -- b, A, array_subscript_handler, pg_catalog
x_pg_locks pg_locks, -- c, C, -, pg_catalog
x__pg_locks _pg_locks, -- b, A, array_subscript_handler, pg_catalog
x_pg_cursors pg_cursors, -- c, C, -, pg_catalog
x__pg_cursors _pg_cursors, -- b, A, array_subscript_handler, pg_catalog
x_pg_available_extensions pg_available_extensions, -- c, C, -, pg_catalog
x__pg_available_extensions _pg_available_extensions, -- b, A, array_subscript_handler, pg_catalog
x_pg_available_extension_versions pg_available_extension_versions, -- c, C, -, pg_catalog
x__pg_available_extension_versions _pg_available_extension_versions, -- b, A, array_subscript_handler, pg_catalog
x_pg_prepared_xacts pg_prepared_xacts, -- c, C, -, pg_catalog
x__pg_prepared_xacts _pg_prepared_xacts, -- b, A, array_subscript_handler, pg_catalog
x_pg_prepared_statements pg_prepared_statements, -- c, C, -, pg_catalog
x__pg_prepared_statements _pg_prepared_statements, -- b, A, array_subscript_handler, pg_catalog
x_pg_seclabels pg_seclabels, -- c, C, -, pg_catalog
x__pg_seclabels _pg_seclabels, -- b, A, array_subscript_handler, pg_catalog
x_pg_settings pg_settings, -- c, C, -, pg_catalog
x__pg_settings _pg_settings, -- b, A, array_subscript_handler, pg_catalog
x_pg_file_settings pg_file_settings, -- c, C, -, pg_catalog
x__pg_file_settings _pg_file_settings, -- b, A, array_subscript_handler, pg_catalog
x_pg_hba_file_rules pg_hba_file_rules, -- c, C, -, pg_catalog
x__pg_hba_file_rules _pg_hba_file_rules, -- b, A, array_subscript_handler, pg_catalog
x_pg_ident_file_mappings pg_ident_file_mappings, -- c, C, -, pg_catalog
x__pg_ident_file_mappings _pg_ident_file_mappings, -- b, A, array_subscript_handler, pg_catalog
x_pg_timezone_abbrevs pg_timezone_abbrevs, -- c, C, -, pg_catalog
x__pg_timezone_abbrevs _pg_timezone_abbrevs, -- b, A, array_subscript_handler, pg_catalog
x_pg_timezone_names pg_timezone_names, -- c, C, -, pg_catalog
x__pg_timezone_names _pg_timezone_names, -- b, A, array_subscript_handler, pg_catalog
x_pg_config pg_config, -- c, C, -, pg_catalog
x__pg_config _pg_config, -- b, A, array_subscript_handler, pg_catalog
x_pg_shmem_allocations pg_shmem_allocations, -- c, C, -, pg_catalog
x__pg_shmem_allocations _pg_shmem_allocations, -- b, A, array_subscript_handler, pg_catalog
x_pg_backend_memory_contexts pg_backend_memory_contexts, -- c, C, -, pg_catalog
x__pg_backend_memory_contexts _pg_backend_memory_contexts, -- b, A, array_subscript_handler, pg_catalog
x_pg_stat_all_tables pg_stat_all_tables, -- c, C, -, pg_catalog
x__pg_stat_all_tables _pg_stat_all_tables, -- b, A, array_subscript_handler, pg_catalog
x_pg_stat_xact_all_tables pg_stat_xact_all_tables, -- c, C, -, pg_catalog
x__pg_stat_xact_all_tables _pg_stat_xact_all_tables, -- b, A, array_subscript_handler, pg_catalog
x_pg_stat_sys_tables pg_stat_sys_tables, -- c, C, -, pg_catalog
x__pg_stat_sys_tables _pg_stat_sys_tables, -- b, A, array_subscript_handler, pg_catalog
x_pg_stat_xact_sys_tables pg_stat_xact_sys_tables, -- c, C, -, pg_catalog
x__pg_stat_xact_sys_tables _pg_stat_xact_sys_tables, -- b, A, array_subscript_handler, pg_catalog
x_pg_stat_user_tables pg_stat_user_tables, -- c, C, -, pg_catalog
x__pg_stat_user_tables _pg_stat_user_tables, -- b, A, array_subscript_handler, pg_catalog
x_pg_stat_xact_user_tables pg_stat_xact_user_tables, -- c, C, -, pg_catalog
x__pg_stat_xact_user_tables _pg_stat_xact_user_tables, -- b, A, array_subscript_handler, pg_catalog
x_pg_statio_all_tables pg_statio_all_tables, -- c, C, -, pg_catalog
x__pg_statio_all_tables _pg_statio_all_tables, -- b, A, array_subscript_handler, pg_catalog
x_pg_statio_sys_tables pg_statio_sys_tables, -- c, C, -, pg_catalog
x__pg_statio_sys_tables _pg_statio_sys_tables, -- b, A, array_subscript_handler, pg_catalog
x_pg_statio_user_tables pg_statio_user_tables, -- c, C, -, pg_catalog
x__pg_statio_user_tables _pg_statio_user_tables, -- b, A, array_subscript_handler, pg_catalog
x_pg_stat_all_indexes pg_stat_all_indexes, -- c, C, -, pg_catalog
x__pg_stat_all_indexes _pg_stat_all_indexes, -- b, A, array_subscript_handler, pg_catalog
x_pg_stat_sys_indexes pg_stat_sys_indexes, -- c, C, -, pg_catalog
x__pg_stat_sys_indexes _pg_stat_sys_indexes, -- b, A, array_subscript_handler, pg_catalog
x_pg_stat_user_indexes pg_stat_user_indexes, -- c, C, -, pg_catalog
x__pg_stat_user_indexes _pg_stat_user_indexes, -- b, A, array_subscript_handler, pg_catalog
x_pg_statio_all_indexes pg_statio_all_indexes, -- c, C, -, pg_catalog
x__pg_statio_all_indexes _pg_statio_all_indexes, -- b, A, array_subscript_handler, pg_catalog
x_pg_statio_sys_indexes pg_statio_sys_indexes, -- c, C, -, pg_catalog
x__pg_statio_sys_indexes _pg_statio_sys_indexes, -- b, A, array_subscript_handler, pg_catalog
x_pg_statio_user_indexes pg_statio_user_indexes, -- c, C, -, pg_catalog
x__pg_statio_user_indexes _pg_statio_user_indexes, -- b, A, array_subscript_handler, pg_catalog
x_pg_statio_all_sequences pg_statio_all_sequences, -- c, C, -, pg_catalog
x__pg_statio_all_sequences _pg_statio_all_sequences, -- b, A, array_subscript_handler, pg_catalog
x_pg_statio_sys_sequences pg_statio_sys_sequences, -- c, C, -, pg_catalog
x__pg_statio_sys_sequences _pg_statio_sys_sequences, -- b, A, array_subscript_handler, pg_catalog
x_pg_statio_user_sequences pg_statio_user_sequences, -- c, C, -, pg_catalog
x__pg_statio_user_sequences _pg_statio_user_sequences, -- b, A, array_subscript_handler, pg_catalog
x_pg_stat_activity pg_stat_activity, -- c, C, -, pg_catalog
x__pg_stat_activity _pg_stat_activity, -- b, A, array_subscript_handler, pg_catalog
x_pg_stat_replication pg_stat_replication, -- c, C, -, pg_catalog
x__pg_stat_replication _pg_stat_replication, -- b, A, array_subscript_handler, pg_catalog
x_pg_stat_slru pg_stat_slru, -- c, C, -, pg_catalog
x__pg_stat_slru _pg_stat_slru, -- b, A, array_subscript_handler, pg_catalog
x_pg_stat_wal_receiver pg_stat_wal_receiver, -- c, C, -, pg_catalog
x__pg_stat_wal_receiver _pg_stat_wal_receiver, -- b, A, array_subscript_handler, pg_catalog
x_pg_stat_recovery_prefetch pg_stat_recovery_prefetch, -- c, C, -, pg_catalog
x__pg_stat_recovery_prefetch _pg_stat_recovery_prefetch, -- b, A, array_subscript_handler, pg_catalog
x_pg_stat_subscription pg_stat_subscription, -- c, C, -, pg_catalog
x__pg_stat_subscription _pg_stat_subscription, -- b, A, array_subscript_handler, pg_catalog
x_pg_stat_ssl pg_stat_ssl, -- c, C, -, pg_catalog
x__pg_stat_ssl _pg_stat_ssl, -- b, A, array_subscript_handler, pg_catalog
x_pg_stat_gssapi pg_stat_gssapi, -- c, C, -, pg_catalog
x__pg_stat_gssapi _pg_stat_gssapi, -- b, A, array_subscript_handler, pg_catalog
x_pg_replication_slots pg_replication_slots, -- c, C, -, pg_catalog
x__pg_replication_slots _pg_replication_slots, -- b, A, array_subscript_handler, pg_catalog
x_pg_stat_replication_slots pg_stat_replication_slots, -- c, C, -, pg_catalog
x__pg_stat_replication_slots _pg_stat_replication_slots, -- b, A, array_subscript_handler, pg_catalog
x_pg_stat_database pg_stat_database, -- c, C, -, pg_catalog
x__pg_stat_database _pg_stat_database, -- b, A, array_subscript_handler, pg_catalog
x_pg_stat_database_conflicts pg_stat_database_conflicts, -- c, C, -, pg_catalog
x__pg_stat_database_conflicts _pg_stat_database_conflicts, -- b, A, array_subscript_handler, pg_catalog
x_pg_stat_user_functions pg_stat_user_functions, -- c, C, -, pg_catalog
x__pg_stat_user_functions _pg_stat_user_functions, -- b, A, array_subscript_handler, pg_catalog
x_pg_stat_xact_user_functions pg_stat_xact_user_functions, -- c, C, -, pg_catalog
x__pg_stat_xact_user_functions _pg_stat_xact_user_functions, -- b, A, array_subscript_handler, pg_catalog
x_pg_stat_archiver pg_stat_archiver, -- c, C, -, pg_catalog
x__pg_stat_archiver _pg_stat_archiver, -- b, A, array_subscript_handler, pg_catalog
x_pg_stat_bgwriter pg_stat_bgwriter, -- c, C, -, pg_catalog
x__pg_stat_bgwriter _pg_stat_bgwriter, -- b, A, array_subscript_handler, pg_catalog
x_pg_stat_wal pg_stat_wal, -- c, C, -, pg_catalog
x__pg_stat_wal _pg_stat_wal, -- b, A, array_subscript_handler, pg_catalog
x_pg_stat_progress_analyze pg_stat_progress_analyze, -- c, C, -, pg_catalog
x__pg_stat_progress_analyze _pg_stat_progress_analyze, -- b, A, array_subscript_handler, pg_catalog
x_pg_stat_progress_vacuum pg_stat_progress_vacuum, -- c, C, -, pg_catalog
x__pg_stat_progress_vacuum _pg_stat_progress_vacuum, -- b, A, array_subscript_handler, pg_catalog
x_pg_stat_progress_cluster pg_stat_progress_cluster, -- c, C, -, pg_catalog
x__pg_stat_progress_cluster _pg_stat_progress_cluster, -- b, A, array_subscript_handler, pg_catalog
x_pg_stat_progress_create_index pg_stat_progress_create_index, -- c, C, -, pg_catalog
x__pg_stat_progress_create_index _pg_stat_progress_create_index, -- b, A, array_subscript_handler, pg_catalog
x_pg_stat_progress_basebackup pg_stat_progress_basebackup, -- c, C, -, pg_catalog
x__pg_stat_progress_basebackup _pg_stat_progress_basebackup, -- b, A, array_subscript_handler, pg_catalog
x_pg_stat_progress_copy pg_stat_progress_copy, -- c, C, -, pg_catalog
x__pg_stat_progress_copy _pg_stat_progress_copy, -- b, A, array_subscript_handler, pg_catalog
x_pg_user_mappings pg_user_mappings, -- c, C, -, pg_catalog
x__pg_user_mappings _pg_user_mappings, -- b, A, array_subscript_handler, pg_catalog
x_pg_replication_origin_status pg_replication_origin_status, -- c, C, -, pg_catalog
x__pg_replication_origin_status _pg_replication_origin_status, -- b, A, array_subscript_handler, pg_catalog
x_pg_stat_subscription_stats pg_stat_subscription_stats, -- c, C, -, pg_catalog
x__pg_stat_subscription_stats _pg_stat_subscription_stats, -- b, A, array_subscript_handler, pg_catalog
x_spheroid spheroid, -- b, U, -, public
x__spheroid _spheroid, -- b, A, array_subscript_handler, public
x_geometry geometry, -- b, U, -, public
x__geometry _geometry, -- b, A, array_subscript_handler, public
x_box3d box3d, -- b, U, -, public
x__box3d _box3d, -- b, A, array_subscript_handler, public
x_box2d box2d, -- b, U, -, public
x__box2d _box2d, -- b, A, array_subscript_handler, public
x_box2df box2df, -- b, U, -, public
x__box2df _box2df, -- b, A, array_subscript_handler, public
x_gidx gidx, -- b, U, -, public
x__gidx _gidx, -- b, A, array_subscript_handler, public
x_geometry_dump geometry_dump, -- c, C, -, public
x__geometry_dump _geometry_dump, -- b, A, array_subscript_handler, public
x_spatial_ref_sys spatial_ref_sys, -- c, C, -, public
x__spatial_ref_sys _spatial_ref_sys, -- b, A, array_subscript_handler, public
x_valid_detail valid_detail, -- c, C, -, public
x__valid_detail _valid_detail, -- b, A, array_subscript_handler, public
x_geography geography, -- b, U, -, public
x__geography _geography, -- b, A, array_subscript_handler, public
x_geography_columns geography_columns, -- c, C, -, public
x__geography_columns _geography_columns, -- b, A, array_subscript_handler, public
x_geometry_columns geometry_columns, -- c, C, -, public
x__geometry_columns _geometry_columns, -- b, A, array_subscript_handler, public
x_typs typs, -- c, C, -, public
x__typs _typs, -- b, A, array_subscript_handler, public
x_files files, -- c, C, -, stage_for_master
x__files _files, -- b, A, array_subscript_handler, stage_for_master
x_template_for_staging_tables template_for_staging_tables, -- c, C, -, public
x__template_for_staging_tables _template_for_staging_tables, -- b, A, array_subscript_handler, public
x_template_for_small_reference_tables template_for_small_reference_tables, -- c, C, -, public
x__template_for_small_reference_tables _template_for_small_reference_tables, -- b, A, array_subscript_handler, public
x_processing_state_enum processing_state_enum, -- e, E, -, public
x__processing_state_enum _processing_state_enum, -- b, A, array_subscript_handler, public
x_row_op_enum row_op_enum, -- e, E, -, public
x__row_op_enum _row_op_enum, -- b, A, array_subscript_handler, public
x_directories directories, -- c, C, -, stage_for_master
x__directories _directories, -- b, A, array_subscript_handler, stage_for_master
x_file_flow_state_enum file_flow_state_enum, -- e, E, -, public
x__file_flow_state_enum _file_flow_state_enum, -- b, A, array_subscript_handler, public
x_template_for_all_tables template_for_all_tables, -- c, C, -, public
x__template_for_all_tables _template_for_all_tables, -- b, A, array_subscript_handler, public
x_gen_id gen_id, -- c, C, -, public
x__gen_id _gen_id, -- b, A, array_subscript_handler, public
x_test_date_diff_gen test_date_diff_gen, -- c, C, -, public
x__test_date_diff_gen _test_date_diff_gen, -- b, A, array_subscript_handler, public
x_template_for_docking_tables template_for_docking_tables, -- c, C, -, public
x__template_for_docking_tables _template_for_docking_tables, -- b, A, array_subscript_handler, public
x_source_meta_agg_enum source_meta_agg_enum, -- e, E, -, public
x__source_meta_agg_enum _source_meta_agg_enum, -- b, A, array_subscript_handler, public
x_source_content_class_enum source_content_class_enum, -- e, E, -, public
x__source_content_class_enum _source_content_class_enum, -- b, A, array_subscript_handler, public
x_source_access_type_enum source_access_type_enum, -- e, E, -, public
x__source_access_type_enum _source_access_type_enum, -- b, A, array_subscript_handler, public
x_citext citext, -- b, S, -, public
x__citext _citext, -- b, A, array_subscript_handler, public
x__hstore _hstore, -- b, A, array_subscript_handler, public
x_ghstore ghstore, -- b, U, -, public
x__ghstore _ghstore, -- b, A, array_subscript_handler, public
x_hstore hstore, -- b, U, hstore_subscript_handler, public
x__ltree _ltree, -- b, A, array_subscript_handler, public
x__ltxtquery _ltxtquery, -- b, A, array_subscript_handler, public
x_ltree_gist ltree_gist, -- b, U, -, public
x__ltree_gist _ltree_gist, -- b, A, array_subscript_handler, public
x_ltree ltree, -- b, U, -, public
x_lquery lquery, -- b, U, -, public
x_ltxtquery ltxtquery, -- b, U, -, public
x_tablefunc_crosstab_2 tablefunc_crosstab_2, -- c, C, -, public
x__tablefunc_crosstab_2 _tablefunc_crosstab_2, -- b, A, array_subscript_handler, public
x_tablefunc_crosstab_3 tablefunc_crosstab_3, -- c, C, -, public
x__tablefunc_crosstab_3 _tablefunc_crosstab_3, -- b, A, array_subscript_handler, public
x_tablefunc_crosstab_4 tablefunc_crosstab_4, -- c, C, -, public
x__tablefunc_crosstab_4 _tablefunc_crosstab_4, -- b, A, array_subscript_handler, public
x_video_files video_files, -- c, C, -, simplified
x__video_files _video_files, -- b, A, array_subscript_handler, simplified
x_computer_os_type_enum computer_os_type_enum, -- e, E, -, public
x__computer_os_type_enum _computer_os_type_enum, -- b, A, array_subscript_handler, public
x_isp_service_type_enum isp_service_type_enum, -- e, E, -, public
x__isp_service_type_enum _isp_service_type_enum, -- b, A, array_subscript_handler, public
x_isp_customer_type_enum isp_customer_type_enum, -- e, E, -, public
x__isp_customer_type_enum _isp_customer_type_enum, -- b, A, array_subscript_handler, public
x_ntext ntext, -- d, S, -, public
x__ntext _ntext, -- b, A, array_subscript_handler, public
x_nnulltext nnulltext, -- d, S, -, public
x__nnulltext _nnulltext, -- b, A, array_subscript_handler, public
x_wsmallint wsmallint, -- d, N, -, public
x__wsmallint _wsmallint, -- b, A, array_subscript_handler, public
x_wmoney wmoney, -- d, N, -, public
x__wmoney _wmoney, -- b, A, array_subscript_handler, public
x_wdecimal14_2 wdecimal14_2, -- d, N, -, public
x__wdecimal14_2 _wdecimal14_2, -- b, A, array_subscript_handler, public
x_video_sub_type_enum video_sub_type_enum, -- e, E, -, simplified
x__video_sub_type_enum _video_sub_type_enum, -- b, A, array_subscript_handler, simplified
x_video_edition_type_enum video_edition_type_enum, -- e, E, -, simplified
x__video_edition_type_enum _video_edition_type_enum, -- b, A, array_subscript_handler, simplified
x_internet_service_providers internet_service_providers, -- c, C, -, simplified
x__internet_service_providers _internet_service_providers, -- b, A, array_subscript_handler, simplified
x_local_networks local_networks, -- c, C, -, simplified
x__local_networks _local_networks, -- b, A, array_subscript_handler, simplified
x_network_adapters network_adapters, -- c, C, -, simplified
x__network_adapters _network_adapters, -- b, A, array_subscript_handler, simplified
x_computers computers, -- c, C, -, simplified
x__computers _computers, -- b, A, array_subscript_handler, simplified
x_volumes volumes, -- c, C, -, simplified
x__volumes _volumes, -- b, A, array_subscript_handler, simplified
x_videos videos, -- c, C, -, simplified
x__videos _videos -- b, A, array_subscript_handler, simplified

);
INSERT INTO t(id, x_bool, x_ntext) VALUES(1,FALSE, 'notnull')