-- https://www.venea.net/web/culture_code
CREATE TABLE receiving_dock.language_codes(
name_culture_dot_name_net TEXT UNIQUE, -- LanguageCode2, Country/RegionCode2
name_english TEXT, --  name in format: language full name [(country / region full name)] in English,
name_native TEXT, --  name composed of: native language full name, [(native country / region full name)],
ison_two_letter_iso_639_1 TEXT,
iso_three_letter_iso_639_2 TEXT,
windows_three_letter_language_name TEXT,
windows_lcid TEXT,
ietf_language_tag_rfc_4646 TEXT
);

INSERT INTO receiving_dock.language_codes VALUES('', 'Invariant Language (Invariant Country)', 'Invariant Language (Invariant Country)', 'iv','ivl','IVL', '127', '');
INSERT INTO receiving_dock.language_codes VALUES('af', 'Afrikaans', 'Afrikaans', 'af','afr','AFK', '54', 'af');
INSERT INTO receiving_dock.language_codes VALUES('af-ZA', 'Afrikaans (South Africa)', 'Afrikaans (Suid-Afrika)', 'af','afr','AFK', '1078', 'af-ZA');
INSERT INTO receiving_dock.language_codes VALUES('am', 'Amharic', 'አማርኛ', 'am','amh','AMH', '94', 'am');
INSERT INTO receiving_dock.language_codes VALUES('am-ET', 'Amharic (Ethiopia)', 'አማርኛ (ኢትዮጵያ)', 'am','amh','AMH', '1118', 'am-ET');
INSERT INTO receiving_dock.language_codes VALUES('ar', 'Arabic', 'العربية', 'ar','ara','ARA', '1', 'ar');
INSERT INTO receiving_dock.language_codes VALUES('ar-AE', 'Arabic (U.A.E.)', 'العربية (الإمارات العربية المتحدة)', 'ar','ara','ARU', '14337', 'ar-AE');
INSERT INTO receiving_dock.language_codes VALUES('ar-BH', 'Arabic (Bahrain)', 'العربية (البحرين)', 'ar','ara','ARH', '15361', 'ar-BH');
INSERT INTO receiving_dock.language_codes VALUES('ar-DZ', 'Arabic (Algeria)', 'العربية (الجزائر)', 'ar','ara','ARG', '5121', 'ar-DZ');
INSERT INTO receiving_dock.language_codes VALUES('ar-EG', 'Arabic (Egypt)', 'العربية (مصر)', 'ar','ara','ARE', '3073', 'ar-EG');
INSERT INTO receiving_dock.language_codes VALUES('ar-IQ', 'Arabic (Iraq)', 'العربية (العراق)', 'ar','ara','ARI', '2049', 'ar-IQ');
INSERT INTO receiving_dock.language_codes VALUES('ar-JO', 'Arabic (Jordan)', 'العربية (الأردن)', 'ar','ara','ARJ', '11265', 'ar-JO');
INSERT INTO receiving_dock.language_codes VALUES('ar-KW', 'Arabic (Kuwait)', 'العربية (الكويت)', 'ar','ara','ARK', '13313', 'ar-KW');
INSERT INTO receiving_dock.language_codes VALUES('ar-LB', 'Arabic (Lebanon)', 'العربية (لبنان)', 'ar','ara','ARB', '12289', 'ar-LB');
INSERT INTO receiving_dock.language_codes VALUES('ar-LY', 'Arabic (Libya)', 'العربية (ليبيا)', 'ar','ara','ARL', '4097', 'ar-LY');
INSERT INTO receiving_dock.language_codes VALUES('ar-MA', 'Arabic (Morocco)', 'العربية (المملكة المغربية)', 'ar','ara','ARM', '6145', 'ar-MA');
INSERT INTO receiving_dock.language_codes VALUES('ar-OM', 'Arabic (Oman)', 'العربية (عمان)', 'ar','ara','ARO', '8193', 'ar-OM');
INSERT INTO receiving_dock.language_codes VALUES('ar-QA', 'Arabic (Qatar)', 'العربية (قطر)', 'ar','ara','ARQ', '16385', 'ar-QA');
INSERT INTO receiving_dock.language_codes VALUES('ar-SA', 'Arabic (Saudi Arabia)', 'العربية (المملكة العربية السعودية)', 'ar','ara','ARA', '1025', 'ar-SA');
INSERT INTO receiving_dock.language_codes VALUES('ar-SY', 'Arabic (Syria)', 'العربية (سوريا)', 'ar','ara','ARS', '10241', 'ar-SY');
INSERT INTO receiving_dock.language_codes VALUES('ar-TN', 'Arabic (Tunisia)', 'العربية (تونس)', 'ar','ara','ART', '7169', 'ar-TN');
INSERT INTO receiving_dock.language_codes VALUES('ar-YE', 'Arabic (Yemen)', 'العربية (اليمن)', 'ar','ara','ARY', '9217', 'ar-YE');
INSERT INTO receiving_dock.language_codes VALUES('arn', 'Mapudungun', 'Mapudungun', 'arn','arn','MPD', '122', 'arn');
INSERT INTO receiving_dock.language_codes VALUES('arn-CL', 'Mapudungun (Chile)', 'Mapudungun (Chile)', 'arn','arn','MPD', '1146', 'arn-CL');
INSERT INTO receiving_dock.language_codes VALUES('as', 'Assamese', 'অসমীয়া', 'as','asm','ASM', '77', 'as');
INSERT INTO receiving_dock.language_codes VALUES('as-IN', 'Assamese (India)', 'অসমীয়া (ভাৰত)', 'as','asm','ASM', '1101', 'as-IN');
INSERT INTO receiving_dock.language_codes VALUES('az', 'Azerbaijani', 'Azərbaycan­ılı', 'az','aze','AZE', '44', 'az');
INSERT INTO receiving_dock.language_codes VALUES('az-Cyrl', 'Azerbaijani (Cyrillic)', 'Азәрбајҹан дили', 'az','aze','AZC', '29740', 'az-Cyrl');
INSERT INTO receiving_dock.language_codes VALUES('az-Cyrl-AZ', 'Azerbaijani (Cyrillic), (Azerbaijan)', 'Азәрбајҹан (Азәрбајҹан)', 'az','aze','AZC', '2092', 'az-Cyrl-AZ');
INSERT INTO receiving_dock.language_codes VALUES('az-Latn', 'Azerbaijani (Latin)', 'Azərbaycan dili (Azərbaycan)', 'az','aze','AZE', '30764', 'az-Latn');
INSERT INTO receiving_dock.language_codes VALUES('az-Latn-AZ', 'Azerbaijani (Latin), (Azerbaijan)', 'Azərbaycan dili (Azərbaycan)', 'az','aze','AZE', '1068', 'az-Latn-AZ');
INSERT INTO receiving_dock.language_codes VALUES('ba', 'Bashkir', 'Башҡорт', 'ba','bak','BAS', '109', 'ba');
INSERT INTO receiving_dock.language_codes VALUES('ba-RU', 'Bashkir (Russia)', 'Башҡорт (Рәсәй)', 'ba','bak','BAS', '1133', 'ba-RU');
INSERT INTO receiving_dock.language_codes VALUES('be', 'Belarusian', 'Беларуская', 'be','bel','BEL', '35', 'be');
INSERT INTO receiving_dock.language_codes VALUES('be-BY', 'Belarusian (Belarus)', 'Беларуская (Беларусь)', 'be','bel','BEL', '1059', 'be-BY');
INSERT INTO receiving_dock.language_codes VALUES('bg', 'Bulgarian', 'български', 'bg','bul','BGR', '2', 'bg');
INSERT INTO receiving_dock.language_codes VALUES('bg-BG', 'Bulgarian (Bulgaria)', 'български (България)', 'bg','bul','BGR', '1026', 'bg-BG');
INSERT INTO receiving_dock.language_codes VALUES('bn', 'Bangla', 'বাংলা', 'bn','bng','BNG', '69', 'bn');
INSERT INTO receiving_dock.language_codes VALUES('bn-BD', 'Bangla (Bangladesh)', 'বাংলা (বাংলাদেশ)', 'bn','bng','BNB', '2117', 'bn-BD');
INSERT INTO receiving_dock.language_codes VALUES('bn-IN', 'Bangla (India)', 'বাংলা (ভারত)', 'bn','bng','BNG', '1093', 'bn-IN');
INSERT INTO receiving_dock.language_codes VALUES('bo', 'Tibetan', 'བོད་ཡིག', 'bo','bod','BOB', '81', 'bo');
INSERT INTO receiving_dock.language_codes VALUES('bo-CN', 'Tibetan (China)', 'བོད་ཡིག (ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ།)', 'bo','bod','BOB', '1105', 'bo-CN');
INSERT INTO receiving_dock.language_codes VALUES('br', 'Breton', 'brezhoneg', 'br','bre','BRE', '126', 'br');
INSERT INTO receiving_dock.language_codes VALUES('br-FR', 'Breton (France)', 'brezhoneg (Frañs)', 'br','bre','BRE', '1150', 'br-FR');
INSERT INTO receiving_dock.language_codes VALUES('bs', 'Bosnian', 'bosanski', 'bs','bsb','BSB', '30746', 'bs');
INSERT INTO receiving_dock.language_codes VALUES('bs-Cyrl', 'Bosnian (Cyrillic)', 'босански', 'bs','bsc','BSC', '25626', 'bs-Cyrl');
INSERT INTO receiving_dock.language_codes VALUES('bs-Cyrl-BA', 'Bosnian (Cyrillic), (Bosnia and Herzegovina)', 'босански (Босна и Херцеговина)', 'bs','bsc','BSC', '8218', 'bs-Cyrl-BA');
INSERT INTO receiving_dock.language_codes VALUES('bs-Latn', 'Bosnian (Latin)', 'bosanski', 'bs','bsb','BSB', '26650', 'bs-Latn');
INSERT INTO receiving_dock.language_codes VALUES('bs-Latn-BA', 'Bosnian (Latin), (Bosnia and Herzegovina)', 'bosanski (Bosna i Hercegovina)', 'bs','bsb','BSB', '5146', 'bs-Latn-BA');
INSERT INTO receiving_dock.language_codes VALUES('ca', 'Catalan', 'Català', 'ca','cat','CAT', '3', 'ca');
INSERT INTO receiving_dock.language_codes VALUES('ca-ES', 'Catalan (Catalan)', 'Català (Català)', 'ca','cat','CAT', '1027', 'ca-ES');
INSERT INTO receiving_dock.language_codes VALUES('ca-ES-valencia', 'Valencian (Spain)', 'Valencià (Espanya)', 'ca','cat','VAL', '2051', 'ca-ES-valencia');
INSERT INTO receiving_dock.language_codes VALUES('chr', 'Cherokee', 'ᏣᎳᎩ', 'chr','chr','CRE', '92', 'chr');
INSERT INTO receiving_dock.language_codes VALUES('chr-Cher', 'Cherokee', 'ᏣᎳᎩ', 'chr','chr','CRE', '31836', 'chr-Cher');
INSERT INTO receiving_dock.language_codes VALUES('chr-Cher-US', 'Cherokee (Cherokee)', 'ᏣᎳᎩ (ᏣᎳᎩ)', 'chr','chr','CRE', '1116', 'chr-Cher-US');
INSERT INTO receiving_dock.language_codes VALUES('co', 'Corsican', 'Corsu', 'co','cos','COS', '131', 'co');
INSERT INTO receiving_dock.language_codes VALUES('co-FR', 'Corsican (France)', 'Corsu (Francia)', 'co','cos','COS', '1155', 'co-FR');
INSERT INTO receiving_dock.language_codes VALUES('cs', 'Czech', 'čeština', 'cs','ces','CSY', '5', 'cs');
INSERT INTO receiving_dock.language_codes VALUES('cs-CZ', 'Czech (Czech Republic)', 'čeština (Česká republika)', 'cs','ces','CSY', '1029', 'cs-CZ');
INSERT INTO receiving_dock.language_codes VALUES('cy', 'Welsh', 'Cymraeg', 'cy','cym','CYM', '82', 'cy');
INSERT INTO receiving_dock.language_codes VALUES('cy-GB', 'Welsh (United Kingdom)', 'Cymraeg (Y Deyrnas Unedig)', 'cy','cym','CYM', '1106', 'cy-GB');
INSERT INTO receiving_dock.language_codes VALUES('da', 'Danish', 'dansk', 'da','dan','DAN', '6', 'da');
INSERT INTO receiving_dock.language_codes VALUES('da-DK', 'Danish (Denmark)', 'dansk (Danmark)', 'da','dan','DAN', '1030', 'da-DK');
INSERT INTO receiving_dock.language_codes VALUES('de', 'German', 'Deutsch', 'de','deu','DEU', '7', 'de');
INSERT INTO receiving_dock.language_codes VALUES('de-AT', 'German (Austria)', 'Deutsch (Österreich)', 'de','deu','DEA', '3079', 'de-AT');
INSERT INTO receiving_dock.language_codes VALUES('de-CH', 'German (Switzerland)', 'Deutsch (Schweiz)', 'de','deu','DES', '2055', 'de-CH');
INSERT INTO receiving_dock.language_codes VALUES('de-DE', 'German (Germany)', 'Deutsch (Deutschland)', 'de','deu','DEU', '1031', 'de-DE');
INSERT INTO receiving_dock.language_codes VALUES('de-LI', 'German (Liechtenstein)', 'Deutsch (Liechtenstein)', 'de','deu','DEC', '5127', 'de-LI');
INSERT INTO receiving_dock.language_codes VALUES('de-LU', 'German (Luxembourg)', 'Deutsch (Luxemburg)', 'de','deu','DEL', '4103', 'de-LU');
INSERT INTO receiving_dock.language_codes VALUES('dsb', 'Lower Sorbian', 'dolnoserbšćina', 'dsb','dsb','DSB', '31790', 'dsb');
INSERT INTO receiving_dock.language_codes VALUES('dsb-DE', 'Lower Sorbian (Germany)', 'dolnoserbšćina (Nimska)', 'dsb','dsb','DSB', '2094', 'dsb-DE');
INSERT INTO receiving_dock.language_codes VALUES('dv', 'Divehi', 'ދިވެހިބަސް', 'dv','div','DIV', '101', 'dv');
INSERT INTO receiving_dock.language_codes VALUES('dv-MV', 'Divehi (Maldives)', 'ދިވެހިބަސް (ދިވެހި ރާއްޖެ)', 'dv','div','DIV', '1125', 'dv-MV');
INSERT INTO receiving_dock.language_codes VALUES('el', 'Greek', 'Ελληνικά', 'el','ell','ELL', '8', 'el');
INSERT INTO receiving_dock.language_codes VALUES('el-GR', 'Greek (Greece)', 'Ελληνικά (Ελλάδα)', 'el','ell','ELL', '1032', 'el-GR');
INSERT INTO receiving_dock.language_codes VALUES('en', 'English', 'English', 'en','eng','ENU', '9', 'en');
INSERT INTO receiving_dock.language_codes VALUES('en-029', 'English (Caribbean)', 'English (Caribbean)', 'en','eng','ENB', '9225', 'en-029');
INSERT INTO receiving_dock.language_codes VALUES('en-AU', 'English (Australia)', 'English (Australia)', 'en','eng','ENA', '3081', 'en-AU');
INSERT INTO receiving_dock.language_codes VALUES('en-BZ', 'English (Belize)', 'English (Belize)', 'en','eng','ENL', '10249', 'en-BZ');
INSERT INTO receiving_dock.language_codes VALUES('en-CA', 'English (Canada)', 'English (Canada)', 'en','eng','ENC', '4105', 'en-CA');
INSERT INTO receiving_dock.language_codes VALUES('en-GB', 'English (United Kingdom)', 'English (United Kingdom)', 'en','eng','ENG', '2057', 'en-GB');
INSERT INTO receiving_dock.language_codes VALUES('en-HK', 'English (Hong Kong)', 'English (Hong Kong)', 'en','eng','ENH', '15369', 'en-HK');
INSERT INTO receiving_dock.language_codes VALUES('en-IE', 'English (Ireland)', 'English (Ireland)', 'en','eng','ENI', '6153', 'en-IE');
INSERT INTO receiving_dock.language_codes VALUES('en-IN', 'English (India)', 'English (India)', 'en','eng','ENN', '16393', 'en-IN');
INSERT INTO receiving_dock.language_codes VALUES('en-JM', 'English (Jamaica)', 'English (Jamaica)', 'en','eng','ENJ', '8201', 'en-JM');
INSERT INTO receiving_dock.language_codes VALUES('en-MY', 'English (Malaysia)', 'English (Malaysia)', 'en','eng','ENM', '17417', 'en-MY');
INSERT INTO receiving_dock.language_codes VALUES('en-NZ', 'English (New Zealand)', 'English (New Zealand)', 'en','eng','ENZ', '5129', 'en-NZ');
INSERT INTO receiving_dock.language_codes VALUES('en-PH', 'English (Philippines)', 'English (Philippines)', 'en','eng','ENP', '13321', 'en-PH');
INSERT INTO receiving_dock.language_codes VALUES('en-SG', 'English (Singapore)', 'English (Singapore)', 'en','eng','ENE', '18441', 'en-SG');
INSERT INTO receiving_dock.language_codes VALUES('en-TT', 'English (Trinidad and Tobago)', 'English (Trinidad and Tobago)', 'en','eng','ENT', '11273', 'en-TT');
INSERT INTO receiving_dock.language_codes VALUES('en-US', 'English (United States)', 'English (United States)', 'en','eng','ENU', '1033', 'en-US');
INSERT INTO receiving_dock.language_codes VALUES('en-ZA', 'English (South Africa)', 'English (South Africa)', 'en','eng','ENS', '7177', 'en-ZA');
INSERT INTO receiving_dock.language_codes VALUES('en-ZW', 'English (Zimbabwe)', 'English (Zimbabwe)', 'en','eng','ENW', '12297', 'en-ZW');
INSERT INTO receiving_dock.language_codes VALUES('es', 'Spanish', 'español', 'es','spa','ESP', '10', 'es');
INSERT INTO receiving_dock.language_codes VALUES('es-419', 'Spanish (Latin America)', 'español (Latinoamérica)', 'es','spa','ESJ', '22538', 'es-419');
INSERT INTO receiving_dock.language_codes VALUES('es-AR', 'Spanish (Argentina)', 'español (Argentina)', 'es','spa','ESS', '11274', 'es-AR');
INSERT INTO receiving_dock.language_codes VALUES('es-BO', 'Spanish (Bolivia)', 'español (Bolivia)', 'es','spa','ESB', '16394', 'es-BO');
INSERT INTO receiving_dock.language_codes VALUES('es-CL', 'Spanish (Chile)', 'español (Chile)', 'es','spa','ESL', '13322', 'es-CL');
INSERT INTO receiving_dock.language_codes VALUES('es-CO', 'Spanish (Colombia)', 'español (Colombia)', 'es','spa','ESO', '9226', 'es-CO');
INSERT INTO receiving_dock.language_codes VALUES('es-CR', 'Spanish (Costa Rica)', 'español (Costa Rica)', 'es','spa','ESC', '5130', 'es-CR');
INSERT INTO receiving_dock.language_codes VALUES('es-DO', 'Spanish (Dominican Republic)', 'español (República Dominicana)', 'es','spa','ESD', '7178', 'es-DO');
INSERT INTO receiving_dock.language_codes VALUES('es-EC', 'Spanish (Ecuador)', 'español (Ecuador)', 'es','spa','ESF', '12298', 'es-EC');
INSERT INTO receiving_dock.language_codes VALUES('es-ES', 'Spanish (Spain), (International Sort)', 'español (España, alfabetización internacional)', 'es','spa','ESN', '3082', 'es-ES');
INSERT INTO receiving_dock.language_codes VALUES('es-GT', 'Spanish (Guatemala)', 'español (Guatemala)', 'es','spa','ESG', '4106', 'es-GT');
INSERT INTO receiving_dock.language_codes VALUES('es-HN', 'Spanish (Honduras)', 'español (Honduras)', 'es','spa','ESH', '18442', 'es-HN');
INSERT INTO receiving_dock.language_codes VALUES('es-MX', 'Spanish (Mexico)', 'español (México)', 'es','spa','ESM', '2058', 'es-MX');
INSERT INTO receiving_dock.language_codes VALUES('es-NI', 'Spanish (Nicaragua)', 'español (Nicaragua)', 'es','spa','ESI', '19466', 'es-NI');
INSERT INTO receiving_dock.language_codes VALUES('es-PA', 'Spanish (Panama)', 'español (Panamá)', 'es','spa','ESA', '6154', 'es-PA');
INSERT INTO receiving_dock.language_codes VALUES('es-PE', 'Spanish (Peru)', 'español (Perú)', 'es','spa','ESR', '10250', 'es-PE');
INSERT INTO receiving_dock.language_codes VALUES('es-PR', 'Spanish (Puerto Rico)', 'español (Puerto Rico)', 'es','spa','ESU', '20490', 'es-PR');
INSERT INTO receiving_dock.language_codes VALUES('es-PY', 'Spanish (Paraguay)', 'español (Paraguay)', 'es','spa','ESZ', '15370', 'es-PY');
INSERT INTO receiving_dock.language_codes VALUES('es-SV', 'Spanish (El Salvador)', 'español (El Salvador)', 'es','spa','ESE', '17418', 'es-SV');
INSERT INTO receiving_dock.language_codes VALUES('es-US', 'Spanish (United States)', 'español (Estados Unidos)', 'es','spa','EST', '21514', 'es-US');
INSERT INTO receiving_dock.language_codes VALUES('es-UY', 'Spanish (Uruguay)', 'español (Uruguay)', 'es','spa','ESY', '14346', 'es-UY');
INSERT INTO receiving_dock.language_codes VALUES('es-VE', 'Spanish (Bolivarian Republic of Venezuela)', 'español (Republica Bolivariana de Venezuela)', 'es','spa','ESV', '8202', 'es-VE');
INSERT INTO receiving_dock.language_codes VALUES('et', 'Estonian', 'eesti', 'et','est','ETI', '37', 'et');
INSERT INTO receiving_dock.language_codes VALUES('et-EE', 'Estonian (Estonia)', 'eesti (Eesti)', 'et','est','ETI', '1061', 'et-EE');
INSERT INTO receiving_dock.language_codes VALUES('eu', 'Basque', 'euskara', 'eu','eus','EUQ', '45', 'eu');
INSERT INTO receiving_dock.language_codes VALUES('eu-ES', 'Basque (Basque)', 'euskara (euskara)', 'eu','eus','EUQ', '1069', 'eu-ES');
INSERT INTO receiving_dock.language_codes VALUES('fa', 'Persian', 'فارسى', 'fa','fas','FAR', '41', 'fa');
INSERT INTO receiving_dock.language_codes VALUES('fa-IR', 'Persian', 'فارسى (ایران)', 'fa','fas','FAR', '1065', 'fa-IR');
INSERT INTO receiving_dock.language_codes VALUES('ff', 'Fulah', 'Fulah', 'ff','ful','FUL', '103', 'ff');
INSERT INTO receiving_dock.language_codes VALUES('ff-Latn', 'Fulah', 'Fulah', 'ff','ful','FUL', '31847', 'ff-Latn');
INSERT INTO receiving_dock.language_codes VALUES('ff-Latn-SN', 'Fulah (Latin), (Senegal)', 'Fulah (Sénégal)', 'ff','ful','FUL', '2151', 'ff-Latn-SN');
INSERT INTO receiving_dock.language_codes VALUES('fi', 'Finnish', 'suomi', 'fi','fin','FIN', '11', 'fi');
INSERT INTO receiving_dock.language_codes VALUES('fi-FI', 'Finnish (Finland)', 'suomi (Suomi)', 'fi','fin','FIN', '1035', 'fi-FI');
INSERT INTO receiving_dock.language_codes VALUES('fil', 'Filipino', 'Filipino', 'fil','fil','FPO', '100', 'fil');
INSERT INTO receiving_dock.language_codes VALUES('fil-PH', 'Filipino (Philippines)', 'Filipino (Pilipinas)', 'fil','fil','FPO', '1124', 'fil-PH');
INSERT INTO receiving_dock.language_codes VALUES('fo', 'Faroese', 'føroyskt', 'fo','fao','FOS', '56', 'fo');
INSERT INTO receiving_dock.language_codes VALUES('fo-FO', 'Faroese (Faroe Islands)', 'føroyskt (Føroyar)', 'fo','fao','FOS', '1080', 'fo-FO');
INSERT INTO receiving_dock.language_codes VALUES('fr', 'French', 'français', 'fr','fra','FRA', '12', 'fr');
INSERT INTO receiving_dock.language_codes VALUES('fr-BE', 'French (Belgium)', 'français (Belgique)', 'fr','fra','FRB', '2060', 'fr-BE');
INSERT INTO receiving_dock.language_codes VALUES('fr-CA', 'French (Canada)', 'français (Canada)', 'fr','fra','FRC', '3084', 'fr-CA');
INSERT INTO receiving_dock.language_codes VALUES('fr-CD', 'French (Congo [DRC])', 'français (Congo [RDC])', 'fr','fra','FRD', '9228', 'fr-CD');
INSERT INTO receiving_dock.language_codes VALUES('fr-CH', 'French (Switzerland)', 'français (Suisse)', 'fr','fra','FRS', '4108', 'fr-CH');
INSERT INTO receiving_dock.language_codes VALUES('fr-CI', 'French (Ivory Coast)', 'français (Côte d’Ivoire)', 'fr','fra','FRI', '12300', 'fr-CI');
INSERT INTO receiving_dock.language_codes VALUES('fr-CM', 'French (Cameroon)', 'français (Cameroun)', 'fr','fra','FRE', '11276', 'fr-CM');
INSERT INTO receiving_dock.language_codes VALUES('fr-FR', 'French (France)', 'français (France)', 'fr','fra','FRA', '1036', 'fr-FR');
INSERT INTO receiving_dock.language_codes VALUES('fr-HT', 'French (Haiti)', 'français (Haïti)', 'fr','fra','FRH', '15372', 'fr-HT');
INSERT INTO receiving_dock.language_codes VALUES('fr-LU', 'French (Luxembourg)', 'français (Luxembourg)', 'fr','fra','FRL', '5132', 'fr-LU');
INSERT INTO receiving_dock.language_codes VALUES('fr-MA', 'French (Morocco)', 'français (Maroc)', 'fr','fra','FRO', '14348', 'fr-MA');
INSERT INTO receiving_dock.language_codes VALUES('fr-MC', 'French (Monaco)', 'français (Principauté de Monaco)', 'fr','fra','FRM', '6156', 'fr-MC');
INSERT INTO receiving_dock.language_codes VALUES('fr-ML', 'French (Mali)', 'français (Mali)', 'fr','fra','FRF', '13324', 'fr-ML');
INSERT INTO receiving_dock.language_codes VALUES('fr-RE', 'French (Réunion)', 'français (Réunion)', 'fr','fra','FRR', '8204', 'fr-RE');
INSERT INTO receiving_dock.language_codes VALUES('fr-SN', 'French (Senegal)', 'français (Sénégal)', 'fr','fra','FRN', '10252', 'fr-SN');
INSERT INTO receiving_dock.language_codes VALUES('fy', 'Frisian', 'Frysk', 'fy','fry','FYN', '98', 'fy');
INSERT INTO receiving_dock.language_codes VALUES('fy-NL', 'Frisian (Netherlands)', 'Frysk (Nederlân)', 'fy','fry','FYN', '1122', 'fy-NL');
INSERT INTO receiving_dock.language_codes VALUES('ga', 'Irish', 'Gaeilge', 'ga','gle','IRE', '60', 'ga');
INSERT INTO receiving_dock.language_codes VALUES('ga-IE', 'Irish (Ireland)', 'Gaeilge (Éire)', 'ga','gle','IRE', '2108', 'ga-IE');
INSERT INTO receiving_dock.language_codes VALUES('gd', 'Scottish Gaelic', 'Gàidhlig', 'gd','gla','GLA', '145', 'gd');
INSERT INTO receiving_dock.language_codes VALUES('gd-GB', 'Scottish Gaelic (United Kingdom)', 'Gàidhlig (An Rìoghachd Aonaichte)', 'gd','gla','GLA', '1169', 'gd-GB');
INSERT INTO receiving_dock.language_codes VALUES('gl', 'Galician', 'galego', 'gl','glg','GLC', '86', 'gl');
INSERT INTO receiving_dock.language_codes VALUES('gl-ES', 'Galician (Galician)', 'galego (galego)', 'gl','glg','GLC', '1110', 'gl-ES');
INSERT INTO receiving_dock.language_codes VALUES('gn', 'Guarani', 'Guarani', 'gn','grn','GRN', '116', 'gn');
INSERT INTO receiving_dock.language_codes VALUES('gn-PY', 'Guarani (Paraguay)', 'Guarani (Paraguái)', 'gn','grn','GRN', '1140', 'gn-PY');
INSERT INTO receiving_dock.language_codes VALUES('gsw', 'Alsatian', 'Elsässisch', 'gsw','gsw','GSW', '132', 'gsw');
INSERT INTO receiving_dock.language_codes VALUES('gsw-FR', 'Alsatian (France)', 'Elsässisch (Frànkrisch)', 'gsw','gsw','GSW', '1156', 'gsw-FR');
INSERT INTO receiving_dock.language_codes VALUES('gu', 'Gujarati', 'ગુજરાતી', 'gu','guj','GUJ', '71', 'gu');
INSERT INTO receiving_dock.language_codes VALUES('gu-IN', 'Gujarati (India)', 'ગુજરાતી (ભારત)', 'gu','guj','GUJ', '1095', 'gu-IN');
INSERT INTO receiving_dock.language_codes VALUES('ha', 'Hausa', 'Hausa', 'ha','hau','HAU', '104', 'ha');
INSERT INTO receiving_dock.language_codes VALUES('ha-Latn', 'Hausa (Latin)', 'Hausa', 'ha','hau','HAU', '31848', 'ha-Latn');
INSERT INTO receiving_dock.language_codes VALUES('ha-Latn-NG', 'Hausa (Latin), (Nigeria)', 'Hausa (Nijeriya)', 'ha','hau','HAU', '1128', 'ha-Latn-NG');
INSERT INTO receiving_dock.language_codes VALUES('haw', 'Hawaiian', 'Hawaiʻi', 'haw','haw','HAW', '117', 'haw');
INSERT INTO receiving_dock.language_codes VALUES('haw-US', 'Hawaiian (United States)', 'Hawaiʻi (ʻAmelika)', 'haw','haw','HAW', '1141', 'haw-US');
INSERT INTO receiving_dock.language_codes VALUES('he', 'Hebrew', 'עברית', 'he','heb','HEB', '13', 'he');
INSERT INTO receiving_dock.language_codes VALUES('he-IL', 'Hebrew (Israel)', 'עברית (ישראל)', 'he','heb','HEB', '1037', 'he-IL');
INSERT INTO receiving_dock.language_codes VALUES('hi', 'Hindi', 'हिंदी', 'hi','hin','HIN', '57', 'hi');
INSERT INTO receiving_dock.language_codes VALUES('hi-IN', 'Hindi (India)', 'हिंदी (भारत)', 'hi','hin','HIN', '1081', 'hi-IN');
INSERT INTO receiving_dock.language_codes VALUES('hr', 'Croatian', 'hrvatski', 'hr','hrv','HRV', '26', 'hr');
INSERT INTO receiving_dock.language_codes VALUES('hr-BA', 'Croatian (Latin), (Bosnia and Herzegovina)', 'hrvatski (Bosna i Hercegovina)', 'hr','hrb','HRB', '4122', 'hr-BA');
INSERT INTO receiving_dock.language_codes VALUES('hr-HR', 'Croatian (Croatia)', 'hrvatski (Hrvatska)', 'hr','hrv','HRV', '1050', 'hr-HR');
INSERT INTO receiving_dock.language_codes VALUES('hsb', 'Upper Sorbian', 'hornjoserbšćina', 'hsb','hsb','HSB', '46', 'hsb');
INSERT INTO receiving_dock.language_codes VALUES('hsb-DE', 'Upper Sorbian (Germany)', 'hornjoserbšćina (Němska)', 'hsb','hsb','HSB', '1070', 'hsb-DE');
INSERT INTO receiving_dock.language_codes VALUES('hu', 'Hungarian', 'magyar', 'hu','hun','HUN', '14', 'hu');
INSERT INTO receiving_dock.language_codes VALUES('hu-HU', 'Hungarian (Hungary)', 'magyar (Magyarország)', 'hu','hun','HUN', '1038', 'hu-HU');
INSERT INTO receiving_dock.language_codes VALUES('hy', 'Armenian', 'Հայերեն', 'hy','hye','HYE', '43', 'hy');
INSERT INTO receiving_dock.language_codes VALUES('hy-AM', 'Armenian (Armenia)', 'Հայերեն (Հայաստան)', 'hy','hye','HYE', '1067', 'hy-AM');
INSERT INTO receiving_dock.language_codes VALUES('id', 'Indonesian', 'Bahasa Indonesia', 'id','ind','IND', '33', 'id');
INSERT INTO receiving_dock.language_codes VALUES('id-ID', 'Indonesian (Indonesia)', 'Bahasa Indonesia (Indonesia)', 'id','ind','IND', '1057', 'id-ID');
INSERT INTO receiving_dock.language_codes VALUES('ig', 'Igbo', 'Igbo', 'ig','ibo','IBO', '112', 'ig');
INSERT INTO receiving_dock.language_codes VALUES('ig-NG', 'Igbo (Nigeria)', 'Igbo (Nigeria)', 'ig','ibo','IBO', '1136', 'ig-NG');
INSERT INTO receiving_dock.language_codes VALUES('ii', 'Yi', 'ꆈꌠꁱꂷ', 'ii','iii','III', '120', 'ii');
INSERT INTO receiving_dock.language_codes VALUES('ii-CN', 'Yi (China)', 'ꆈꌠꁱꂷ (ꍏꉸꏓꂱꇭꉼꇩ)', 'ii','iii','III', '1144', 'ii-CN');
INSERT INTO receiving_dock.language_codes VALUES('is', 'Icelandic', 'íslenska', 'is','isl','ISL', '15', 'is');
INSERT INTO receiving_dock.language_codes VALUES('is-IS', 'Icelandic (Iceland)', 'íslenska (Ísland)', 'is','isl','ISL', '1039', 'is-IS');
INSERT INTO receiving_dock.language_codes VALUES('it', 'Italian', 'italiano', 'it','ita','ITA', '16', 'it');
INSERT INTO receiving_dock.language_codes VALUES('it-CH', 'Italian (Switzerland)', 'italiano (Svizzera)', 'it','ita','ITS', '2064', 'it-CH');
INSERT INTO receiving_dock.language_codes VALUES('it-IT', 'Italian (Italy)', 'italiano (Italia)', 'it','ita','ITA', '1040', 'it-IT');
INSERT INTO receiving_dock.language_codes VALUES('iu', 'Inuktitut', 'Inuktitut', 'iu','iku','IUK', '93', 'iu');
INSERT INTO receiving_dock.language_codes VALUES('iu-Cans', 'Inuktitut (Syllabics)', 'ᐃᓄᒃᑎᑐᑦ', 'iu','iku','IUS', '30813', 'iu-Cans');
INSERT INTO receiving_dock.language_codes VALUES('iu-Cans-CA', 'Inuktitut (Syllabics), (Canada)', 'ᐃᓄᒃᑎᑐᑦ (ᑲᓇᑕᒥ)', 'iu','iku','IUS', '1117', 'iu-Cans-CA');
INSERT INTO receiving_dock.language_codes VALUES('iu-Latn', 'Inuktitut (Latin)', 'Inuktitut', 'iu','iku','IUK', '31837', 'iu-Latn');
INSERT INTO receiving_dock.language_codes VALUES('iu-Latn-CA', 'Inuktitut (Latin), (Canada)', 'Inuktitut (Kanatami)', 'iu','iku','IUK', '2141', 'iu-Latn-CA');
INSERT INTO receiving_dock.language_codes VALUES('ja', 'Japanese', '日本語', 'ja','jpn','JPN', '17', 'ja');
INSERT INTO receiving_dock.language_codes VALUES('ja-JP', 'Japanese (Japan)', '日本語 (日本)', 'ja','jpn','JPN', '1041', 'ja-JP');
INSERT INTO receiving_dock.language_codes VALUES('jv', 'Javanese', 'Basa Jawa', 'jv','jav','JAV', '4096', 'jv');
INSERT INTO receiving_dock.language_codes VALUES('jv-Latn', 'Javanese', 'Basa Jawa', 'jv','jav','JAV', '4096', 'jv-Latn');
INSERT INTO receiving_dock.language_codes VALUES('jv-Latn-ID', 'Javanese (Indonesia)', 'Basa Jawa (Indonesia)', 'jv','jav','JAV', '4096', 'jv-Latn-ID');
INSERT INTO receiving_dock.language_codes VALUES('ka', 'Georgian', 'ქართული', 'ka','kat','KAT', '55', 'ka');
INSERT INTO receiving_dock.language_codes VALUES('ka-GE', 'Georgian (Georgia)', 'ქართული (საქართველო)', 'ka','kat','KAT', '1079', 'ka-GE');
INSERT INTO receiving_dock.language_codes VALUES('kk', 'Kazakh', 'Қазақ', 'kk','kaz','KKZ', '63', 'kk');
INSERT INTO receiving_dock.language_codes VALUES('kk-KZ', 'Kazakh (Kazakhstan)', 'Қазақ (Қазақстан)', 'kk','kaz','KKZ', '1087', 'kk-KZ');
INSERT INTO receiving_dock.language_codes VALUES('kl', 'Greenlandic', 'kalaallisut', 'kl','kal','KAL', '111', 'kl');
INSERT INTO receiving_dock.language_codes VALUES('kl-GL', 'Greenlandic (Greenland)', 'kalaallisut (Kalaallit Nunaat)', 'kl','kal','KAL', '1135', 'kl-GL');
INSERT INTO receiving_dock.language_codes VALUES('km', 'Khmer', 'ភាសាខ្មែរ', 'km','khm','KHM', '83', 'km');
INSERT INTO receiving_dock.language_codes VALUES('km-KH', 'Khmer (Cambodia)', 'ភាសាខ្មែរ (កម្ពុជា)', 'km','khm','KHM', '1107', 'km-KH');
INSERT INTO receiving_dock.language_codes VALUES('kn', 'Kannada', 'ಕನ್ನಡ', 'kn','kan','KDI', '75', 'kn');
INSERT INTO receiving_dock.language_codes VALUES('kn-IN', 'Kannada (India)', 'ಕನ್ನಡ (ಭಾರತ)', 'kn','kan','KDI', '1099', 'kn-IN');
INSERT INTO receiving_dock.language_codes VALUES('ko', 'Korean', '한국어', 'ko','kor','KOR', '18', 'ko');
INSERT INTO receiving_dock.language_codes VALUES('ko-KR', 'Korean (Korea)', '한국어(대한민국)', 'ko','kor','KOR', '1042', 'ko-KR');
INSERT INTO receiving_dock.language_codes VALUES('kok', 'Konkani', 'कोंकणी', 'kok','kok','KNK', '87', 'kok');
INSERT INTO receiving_dock.language_codes VALUES('kok-IN', 'Konkani (India)', 'कोंकणी (भारत)', 'kok','kok','KNK', '1111', 'kok-IN');
INSERT INTO receiving_dock.language_codes VALUES('ku', 'Central Kurdish', 'کوردیی ناوەڕاست', 'ku','kur','KUR', '146', 'ku');
INSERT INTO receiving_dock.language_codes VALUES('ku-Arab', 'Central Kurdish', 'کوردیی ناوەڕاست', 'ku','kur','KUR', '31890', 'ku-Arab');
INSERT INTO receiving_dock.language_codes VALUES('ku-Arab-IQ', 'Central Kurdish (Iraq)', 'کوردیی ناوەڕاست (کوردستان)', 'ku','kur','KUR', '1170', 'ku-Arab-IQ');
INSERT INTO receiving_dock.language_codes VALUES('ky', 'Kyrgyz', 'Кыргыз', 'ky','kir','KYR', '64', 'ky');
INSERT INTO receiving_dock.language_codes VALUES('ky-KG', 'Kyrgyz (Kyrgyzstan)', 'Кыргыз (Кыргызстан)', 'ky','kir','KYR', '1088', 'ky-KG');
INSERT INTO receiving_dock.language_codes VALUES('lb', 'Luxembourgish', 'Lëtzebuergesch', 'lb','ltz','LBX', '110', 'lb');
INSERT INTO receiving_dock.language_codes VALUES('lb-LU', 'Luxembourgish (Luxembourg)', 'Lëtzebuergesch (Lëtzebuerg)', 'lb','ltz','LBX', '1134', 'lb-LU');
INSERT INTO receiving_dock.language_codes VALUES('lo', 'Lao', 'ພາສາລາວ', 'lo','lao','LAO', '84', 'lo');
INSERT INTO receiving_dock.language_codes VALUES('lo-LA', 'Lao (Lao PDR)', 'ພາສາລາວ (ສປປ ລາວ)', 'lo','lao','LAO', '1108', 'lo-LA');
INSERT INTO receiving_dock.language_codes VALUES('lt', 'Lithuanian', 'lietuvių', 'lt','lit','LTH', '39', 'lt');
INSERT INTO receiving_dock.language_codes VALUES('lt-LT', 'Lithuanian (Lithuania)', 'lietuvių (Lietuva)', 'lt','lit','LTH', '1063', 'lt-LT');
INSERT INTO receiving_dock.language_codes VALUES('lv', 'Latvian', 'latviešu', 'lv','lav','LVI', '38', 'lv');
INSERT INTO receiving_dock.language_codes VALUES('lv-LV', 'Latvian (Latvia)', 'latviešu (Latvija)', 'lv','lav','LVI', '1062', 'lv-LV');
INSERT INTO receiving_dock.language_codes VALUES('mg', 'Malagasy', 'Malagasy', 'mg','mlg','MLG', '4096', 'mg');
INSERT INTO receiving_dock.language_codes VALUES('mg-MG', 'Malagasy (Madagascar)', 'Malagasy (Madagasikara)', 'mg','mlg','MLG', '4096', 'mg-MG');
INSERT INTO receiving_dock.language_codes VALUES('mi', 'Maori', 'Reo Māori', 'mi','mri','MRI', '129', 'mi');
INSERT INTO receiving_dock.language_codes VALUES('mi-NZ', 'Maori (New Zealand)', 'Reo Māori (Aotearoa)', 'mi','mri','MRI', '1153', 'mi-NZ');
INSERT INTO receiving_dock.language_codes VALUES('mk', 'Macedonian (Former Yugoslav Republic of Macedonia)', 'македонски јазик', 'mk','mkd','MKI', '47', 'mk');
INSERT INTO receiving_dock.language_codes VALUES('mk-MK', 'Macedonian (Former Yugoslav Republic of Macedonia)', 'македонски јазик (Македонија)', 'mk','mkd','MKI', '1071', 'mk-MK');
INSERT INTO receiving_dock.language_codes VALUES('ml', 'Malayalam', 'മലയാളം', 'ml','mym','MYM', '76', 'ml');
INSERT INTO receiving_dock.language_codes VALUES('ml-IN', 'Malayalam (India)', 'മലയാളം (ഭാരതം)', 'ml','mym','MYM', '1100', 'ml-IN');
INSERT INTO receiving_dock.language_codes VALUES('mn', 'Mongolian', 'Монгол хэл', 'mn','mon','MON', '80', 'mn');
INSERT INTO receiving_dock.language_codes VALUES('mn-Cyrl', 'Mongolian (Cyrillic)', 'Монгол хэл', 'mn','mon','MNN', '30800', 'mn-Cyrl');
INSERT INTO receiving_dock.language_codes VALUES('mn-MN', 'Mongolian (Cyrillic), (Mongolia)', 'Монгол хэл (Монгол улс)', 'mn','mon','MNN', '1104', 'mn-MN');
INSERT INTO receiving_dock.language_codes VALUES('mn-Mong', 'Mongolian (Traditional Mongolian)', 'ᠮᠤᠨᠭᠭᠤᠯ ᠬᠡᠯᠡ', 'mn','mon','MNG', '31824', 'mn-Mong');
INSERT INTO receiving_dock.language_codes VALUES('mn-Mong-CN', 'Mongolian (Traditional Mongolian), (China)', 'ᠮᠤᠨᠭᠭᠤᠯ ᠬᠡᠯᠡ (ᠪᠦᠭᠦᠳᠡ ᠨᠠᠢᠷᠠᠮᠳᠠᠬᠤ ᠳᠤᠮᠳᠠᠳᠤ ᠠᠷᠠᠳ ᠣᠯᠣᠰ)', 'mn','mon','MNG', '2128', 'mn-Mong-CN');
INSERT INTO receiving_dock.language_codes VALUES('mn-Mong-MN', 'Mongolian (Traditional Mongolian), (Mongolia)', 'ᠮᠤᠨᠭᠭᠤᠯ ᠬᠡᠯᠡ (ᠮᠤᠨᠭᠭᠤᠯ ᠣᠯᠣᠰ)', 'mn','mon','MNM', '3152', 'mn-Mong-MN');
INSERT INTO receiving_dock.language_codes VALUES('moh', 'Mohawk', 'Kanien''kéha', 'moh','moh','MWK', '124', 'moh');
INSERT INTO receiving_dock.language_codes VALUES('moh-CA', 'Mohawk (Mohawk)', 'Kanien''kéha', 'moh','moh','MWK', '1148', 'moh-CA');
INSERT INTO receiving_dock.language_codes VALUES('mr', 'Marathi', 'मराठी', 'mr','mar','MAR', '78', 'mr');
INSERT INTO receiving_dock.language_codes VALUES('mr-IN', 'Marathi (India)', 'मराठी (भारत)', 'mr','mar','MAR', '1102', 'mr-IN');
INSERT INTO receiving_dock.language_codes VALUES('ms', 'Malay', 'Bahasa Melayu', 'ms','msa','MSL', '62', 'ms');
INSERT INTO receiving_dock.language_codes VALUES('ms-BN', 'Malay (Brunei Darussalam)', 'Bahasa Melayu (Brunei Darussalam)', 'ms','msa','MSB', '2110', 'ms-BN');
INSERT INTO receiving_dock.language_codes VALUES('ms-MY', 'Malay (Malaysia)', 'Bahasa Melayu (Malaysia)', 'ms','msa','MSL', '1086', 'ms-MY');
INSERT INTO receiving_dock.language_codes VALUES('mt', 'Maltese', 'Malti', 'mt','mlt','MLT', '58', 'mt');
INSERT INTO receiving_dock.language_codes VALUES('mt-MT', 'Maltese (Malta)', 'Malti (Malta)', 'mt','mlt','MLT', '1082', 'mt-MT');
INSERT INTO receiving_dock.language_codes VALUES('my', 'Burmese', 'ဗမာ', 'my','mya','MYA', '85', 'my');
INSERT INTO receiving_dock.language_codes VALUES('my-MM', 'Burmese (Myanmar)', 'ဗမာ (မြန်မာ)', 'my','mya','MYA', '1109', 'my-MM');
INSERT INTO receiving_dock.language_codes VALUES('nb', 'Norwegian (Bokmål)', 'norsk (bokmål)', 'nb','nob','NOR', '31764', 'nb');
INSERT INTO receiving_dock.language_codes VALUES('nb-NO', 'Norwegian, Bokmål (Norway)', 'norsk, bokmål (Norge)', 'nb','nob','NOR', '1044', 'nb-NO');
INSERT INTO receiving_dock.language_codes VALUES('ne', 'Nepali', 'नेपाली', 'ne','nep','NEP', '97', 'ne');
INSERT INTO receiving_dock.language_codes VALUES('ne-IN', 'Nepali (India)', 'नेपाली (भारत)', 'ne','nep','NEI', '2145', 'ne-IN');
INSERT INTO receiving_dock.language_codes VALUES('ne-NP', 'Nepali (Nepal)', 'नेपाली (नेपाल)', 'ne','nep','NEP', '1121', 'ne-NP');
INSERT INTO receiving_dock.language_codes VALUES('nl', 'Dutch', 'Nederlands', 'nl','nld','NLD', '19', 'nl');
INSERT INTO receiving_dock.language_codes VALUES('nl-BE', 'Dutch (Belgium)', 'Nederlands (België)', 'nl','nld','NLB', '2067', 'nl-BE');
INSERT INTO receiving_dock.language_codes VALUES('nl-NL', 'Dutch (Netherlands)', 'Nederlands (Nederland)', 'nl','nld','NLD', '1043', 'nl-NL');
INSERT INTO receiving_dock.language_codes VALUES('nn', 'Norwegian (Nynorsk)', 'norsk (nynorsk)', 'nn','nno','NON', '30740', 'nn');
INSERT INTO receiving_dock.language_codes VALUES('nn-NO', 'Norwegian, Nynorsk (Norway)', 'norsk, nynorsk (Noreg)', 'nn','nno','NON', '2068', 'nn-NO');
INSERT INTO receiving_dock.language_codes VALUES('no', 'Norwegian', 'norsk', 'nb','nob','NOR', '20', 'no');
INSERT INTO receiving_dock.language_codes VALUES('nqo', 'N''ko', 'ߒߞߏ', 'nqo','nqo','NQO', '4096', 'nqo');
INSERT INTO receiving_dock.language_codes VALUES('nqo-GN', 'N''ko (Guinea)', 'ߒߞߏ (ߖߌ߬ߣߍ߬ ߞߊ߲ߓߍ߲)', 'nqo','nqo','NQO', '4096', 'nqo-GN');
INSERT INTO receiving_dock.language_codes VALUES('nso', 'Sesotho sa Leboa', 'Sesotho sa Leboa', 'nso','nso','NSO', '108', 'nso');
INSERT INTO receiving_dock.language_codes VALUES('nso-ZA', 'Sesotho sa Leboa (South Africa)', 'Sesotho sa Leboa (Afrika Borwa)', 'nso','nso','NSO', '1132', 'nso-ZA');
INSERT INTO receiving_dock.language_codes VALUES('oc', 'Occitan', 'Occitan', 'oc','oci','OCI', '130', 'oc');
INSERT INTO receiving_dock.language_codes VALUES('oc-FR', 'Occitan (France)', 'Occitan (França)', 'oc','oci','OCI', '1154', 'oc-FR');
INSERT INTO receiving_dock.language_codes VALUES('om', 'Oromo', 'Oromoo', 'om','orm','ORM', '114', 'om');
INSERT INTO receiving_dock.language_codes VALUES('om-ET', 'Oromo (Ethiopia)', 'Oromoo (Itoophiyaa)', 'om','orm','ORM', '1138', 'om-ET');
INSERT INTO receiving_dock.language_codes VALUES('or', 'Odia', 'ଓଡ଼ିଆ', 'or','ori','ORI', '72', 'or');
INSERT INTO receiving_dock.language_codes VALUES('or-IN', 'Odia (India)', 'ଓଡ଼ିଆ (ଭାରତ)', 'or','ori','ORI', '1096', 'or-IN');
INSERT INTO receiving_dock.language_codes VALUES('pa', 'Punjabi', 'ਪੰਜਾਬੀ', 'pa','pan','PAN', '70', 'pa');
INSERT INTO receiving_dock.language_codes VALUES('pa-Arab', 'Punjabi', 'پنجابی', 'pa','pan','PAN', '31814', 'pa-Arab');
INSERT INTO receiving_dock.language_codes VALUES('pa-Arab-PK', 'Punjabi (Pakistan)', 'پنجابی (پاکستان)', 'pa','pan','PAN', '2118', 'pa-Arab-PK');
INSERT INTO receiving_dock.language_codes VALUES('pa-IN', 'Punjabi (India)', 'ਪੰਜਾਬੀ (ਭਾਰਤ)', 'pa','pan','PAN', '1094', 'pa-IN');
INSERT INTO receiving_dock.language_codes VALUES('pl', 'Polish', 'polski', 'pl','pol','PLK', '21', 'pl');
INSERT INTO receiving_dock.language_codes VALUES('pl-PL', 'Polish (Poland)', 'polski (Polska)', 'pl','pol','PLK', '1045', 'pl-PL');
INSERT INTO receiving_dock.language_codes VALUES('prs', 'Dari', 'درى', 'prs','prs','PRS', '140', 'prs');
INSERT INTO receiving_dock.language_codes VALUES('prs-AF', 'Dari (Afghanistan)', 'درى (افغانستان)', 'prs','prs','PRS', '1164', 'prs-AF');
INSERT INTO receiving_dock.language_codes VALUES('ps', 'Pashto', 'پښتو', 'ps','pus','PAS', '99', 'ps');
INSERT INTO receiving_dock.language_codes VALUES('ps-AF', 'Pashto (Afghanistan)', 'پښتو (افغانستان)', 'ps','pus','PAS', '1123', 'ps-AF');
INSERT INTO receiving_dock.language_codes VALUES('pt', 'Portuguese', 'português', 'pt','por','PTB', '22', 'pt');
INSERT INTO receiving_dock.language_codes VALUES('pt-AO', 'Portuguese (Angola)', 'português (Angola)', 'pt','por','PTA', '4096', 'pt-AO');
INSERT INTO receiving_dock.language_codes VALUES('pt-BR', 'Portuguese (Brazil)', 'português (Brasil)', 'pt','por','PTB', '1046', 'pt-BR');
INSERT INTO receiving_dock.language_codes VALUES('pt-PT', 'Portuguese (Portugal)', 'português (Portugal)', 'pt','por','PTG', '2070', 'pt-PT');
INSERT INTO receiving_dock.language_codes VALUES('qut', 'K''iche''', 'K''iche''', 'qut','qut','QUT', '134', 'qut');
INSERT INTO receiving_dock.language_codes VALUES('qut-GT', 'K''iche'' (Guatemala)', 'K''iche'' (Guatemala)', 'qut','qut','QUT', '1158', 'qut-GT');
INSERT INTO receiving_dock.language_codes VALUES('quz', 'Quechua', 'runasimi', 'quz','qub','QUB', '107', 'quz');
INSERT INTO receiving_dock.language_codes VALUES('quz-BO', 'Quechua (Bolivia)', 'runasimi (Qullasuyu)', 'quz','qub','QUB', '1131', 'quz-BO');
INSERT INTO receiving_dock.language_codes VALUES('quz-EC', 'Quichua (Ecuador)', 'runa shimi (Ecuador Suyu)', 'quz','que','QUE', '2155', 'quz-EC');
INSERT INTO receiving_dock.language_codes VALUES('quz-PE', 'Quechua (Peru)', 'runasimi (Peru)', 'quz','qup','QUP', '3179', 'quz-PE');
INSERT INTO receiving_dock.language_codes VALUES('rm', 'Romansh', 'Rumantsch', 'rm','roh','RMC', '23', 'rm');
INSERT INTO receiving_dock.language_codes VALUES('rm-CH', 'Romansh (Switzerland)', 'Rumantsch (Svizra)', 'rm','roh','RMC', '1047', 'rm-CH');
INSERT INTO receiving_dock.language_codes VALUES('ro', 'Romanian', 'română', 'ro','ron','ROM', '24', 'ro');
INSERT INTO receiving_dock.language_codes VALUES('ro-MD', 'Romanian (Moldova)', 'română (Republica Moldova)', 'ro','ron','ROD', '2072', 'ro-MD');
INSERT INTO receiving_dock.language_codes VALUES('ro-RO', 'Romanian (Romania)', 'română (România)', 'ro','ron','ROM', '1048', 'ro-RO');
INSERT INTO receiving_dock.language_codes VALUES('ru', 'Russian', 'русский', 'ru','rus','RUS', '25', 'ru');
INSERT INTO receiving_dock.language_codes VALUES('ru-RU', 'Russian (Russia)', 'русский (Россия)', 'ru','rus','RUS', '1049', 'ru-RU');
INSERT INTO receiving_dock.language_codes VALUES('rw', 'Kinyarwanda', 'Kinyarwanda', 'rw','kin','KIN', '135', 'rw');
INSERT INTO receiving_dock.language_codes VALUES('rw-RW', 'Kinyarwanda (Rwanda)', 'Kinyarwanda (Rwanda)', 'rw','kin','KIN', '1159', 'rw-RW');
INSERT INTO receiving_dock.language_codes VALUES('sa', 'Sanskrit', 'संस्कृत', 'sa','san','SAN', '79', 'sa');
INSERT INTO receiving_dock.language_codes VALUES('sa-IN', 'Sanskrit (India)', 'संस्कृत (भारतम्)', 'sa','san','SAN', '1103', 'sa-IN');
INSERT INTO receiving_dock.language_codes VALUES('sah', 'Sakha', 'Саха', 'sah','sah','SAH', '133', 'sah');
INSERT INTO receiving_dock.language_codes VALUES('sah-RU', 'Sakha (Russia)', 'Саха (Россия)', 'sah','sah','SAH', '1157', 'sah-RU');
INSERT INTO receiving_dock.language_codes VALUES('sd', 'Sindhi', 'سنڌي', 'sd','sin','SIN', '89', 'sd');
INSERT INTO receiving_dock.language_codes VALUES('sd-Arab', 'Sindhi', 'سنڌي', 'sd','sin','SIN', '31833', 'sd-Arab');
INSERT INTO receiving_dock.language_codes VALUES('sd-Arab-PK', 'Sindhi (Pakistan)', 'سنڌي (پاکستان)', 'sd','sin','SIN', '2137', 'sd-Arab-PK');
INSERT INTO receiving_dock.language_codes VALUES('se', 'Sami (Northern)', 'davvisámegiella', 'se','sme','SME', '59', 'se');
INSERT INTO receiving_dock.language_codes VALUES('se-FI', 'Sami, Northern (Finland)', 'davvisámegiella (Suopma)', 'se','sme','SMG', '3131', 'se-FI');
INSERT INTO receiving_dock.language_codes VALUES('se-NO', 'Sami, Northern (Norway)', 'davvisámegiella (Norga)', 'se','sme','SME', '1083', 'se-NO');
INSERT INTO receiving_dock.language_codes VALUES('se-SE', 'Sami, Northern (Sweden)', 'davvisámegiella (Ruoŧŧa)', 'se','sme','SMF', '2107', 'se-SE');
INSERT INTO receiving_dock.language_codes VALUES('si', 'Sinhala', 'සිංහල', 'si','sin','SIN', '91', 'si');
INSERT INTO receiving_dock.language_codes VALUES('si-LK', 'Sinhala (Sri Lanka)', 'සිංහල (ශ්‍රී ලංකා)', 'si','sin','SIN', '1115', 'si-LK');
INSERT INTO receiving_dock.language_codes VALUES('sk', 'Slovak', 'slovenčina', 'sk','slk','SKY', '27', 'sk');
INSERT INTO receiving_dock.language_codes VALUES('sk-SK', 'Slovak (Slovakia)', 'slovenčina (Slovenská republika)', 'sk','slk','SKY', '1051', 'sk-SK');
INSERT INTO receiving_dock.language_codes VALUES('sl', 'Slovenian', 'slovenščina', 'sl','slv','SLV', '36', 'sl');
INSERT INTO receiving_dock.language_codes VALUES('sl-SI', 'Slovenian (Slovenia)', 'slovenščina (Slovenija)', 'sl','slv','SLV', '1060', 'sl-SI');
INSERT INTO receiving_dock.language_codes VALUES('sma', 'Sami (Southern)', 'åarjelsaemiengïele', 'sma','sma','SMB', '30779', 'sma');
INSERT INTO receiving_dock.language_codes VALUES('sma-NO', 'Sami, Southern (Norway)', 'åarjelsaemiengïele (Nöörje)', 'sma','sma','SMA', '6203', 'sma-NO');
INSERT INTO receiving_dock.language_codes VALUES('sma-SE', 'Sami, Southern (Sweden)', 'åarjelsaemiengïele (Sveerje)', 'sma','sma','SMB', '7227', 'sma-SE');
INSERT INTO receiving_dock.language_codes VALUES('smj', 'Sami (Lule)', 'julevusámegiella', 'smj','smj','SMK', '31803', 'smj');
INSERT INTO receiving_dock.language_codes VALUES('smj-NO', 'Sami, Lule (Norway)', 'julevusámegiella (Vuodna)', 'smj','smj','SMJ', '4155', 'smj-NO');
INSERT INTO receiving_dock.language_codes VALUES('smj-SE', 'Sami, Lule (Sweden)', 'julevusámegiella (Svierik)', 'smj','smj','SMK', '5179', 'smj-SE');
INSERT INTO receiving_dock.language_codes VALUES('smn', 'Sami (Inari)', 'sämikielâ', 'smn','smn','SMN', '28731', 'smn');
INSERT INTO receiving_dock.language_codes VALUES('smn-FI', 'Sami, Inari (Finland)', 'sämikielâ (Suomâ)', 'smn','smn','SMN', '9275', 'smn-FI');
INSERT INTO receiving_dock.language_codes VALUES('sms', 'Sami (Skolt)', 'sää´mǩiõll', 'sms','sms','SMS', '29755', 'sms');
INSERT INTO receiving_dock.language_codes VALUES('sms-FI', 'Sami, Skolt (Finland)', 'sää´mǩiõll (Lää´ddjânnam)', 'sms','sms','SMS', '8251', 'sms-FI');
INSERT INTO receiving_dock.language_codes VALUES('sn', 'Shona', 'chiShona', 'sn','sna','SNA', '4096', 'sn');
INSERT INTO receiving_dock.language_codes VALUES('sn-Latn', 'Shona (Latin)', 'chiShona (Latin)', 'sn','sna','SNA', '4096', 'sn-Latn');
INSERT INTO receiving_dock.language_codes VALUES('sn-Latn-ZW', 'Shona (Latin), (Zimbabwe)', 'chiShona (Latin, Zimbabwe)', 'sn','sna','SNA', '4096', 'sn-Latn-ZW');
INSERT INTO receiving_dock.language_codes VALUES('so', 'Somali', 'Soomaali', 'so','som','SOM', '119', 'so');
INSERT INTO receiving_dock.language_codes VALUES('so-SO', 'Somali (Somalia)', 'Soomaali (Soomaaliya)', 'so','som','SOM', '1143', 'so-SO');
INSERT INTO receiving_dock.language_codes VALUES('sq', 'Albanian', 'Shqip', 'sq','sqi','SQI', '28', 'sq');
INSERT INTO receiving_dock.language_codes VALUES('sq-AL', 'Albanian (Albania)', 'Shqip (Shqipëria)', 'sq','sqi','SQI', '1052', 'sq-AL');
INSERT INTO receiving_dock.language_codes VALUES('sr', 'Serbian', 'srpski', 'sr','srp','SRB', '31770', 'sr');
INSERT INTO receiving_dock.language_codes VALUES('sr-Cyrl', 'Serbian (Cyrillic)', 'српски', 'sr','srp','SRO', '27674', 'sr-Cyrl');
INSERT INTO receiving_dock.language_codes VALUES('sr-Cyrl-BA', 'Serbian (Cyrillic), (Bosnia and Herzegovina)', 'српски (Босна и Херцеговина)', 'sr','srn','SRN', '7194', 'sr-Cyrl-BA');
INSERT INTO receiving_dock.language_codes VALUES('sr-Cyrl-CS', 'Serbian (Cyrillic), (Serbia and Montenegro (Former))', 'српски (Србија и Црна Гора (Бивша))', 'sr','srp','SRB', '3098', 'sr-Cyrl-CS');
INSERT INTO receiving_dock.language_codes VALUES('sr-Cyrl-ME', 'Serbian (Cyrillic), (Montenegro)', 'српски (Црна Гора)', 'sr','srp','SRQ', '12314', 'sr-Cyrl-ME');
INSERT INTO receiving_dock.language_codes VALUES('sr-Cyrl-RS', 'Serbian (Cyrillic), (Serbia)', 'српски (Србија)', 'sr','srp','SRO', '10266', 'sr-Cyrl-RS');
INSERT INTO receiving_dock.language_codes VALUES('sr-Latn', 'Serbian (Latin)', 'srpski', 'sr','srp','SRM', '28698', 'sr-Latn');
INSERT INTO receiving_dock.language_codes VALUES('sr-Latn-BA', 'Serbian (Latin), (Bosnia and Herzegovina)', 'srpski (Bosna i Hercegovina)', 'sr','srs','SRS', '6170', 'sr-Latn-BA');
INSERT INTO receiving_dock.language_codes VALUES('sr-Latn-CS', 'Serbian (Latin), (Serbia and Montenegro (Former))', 'srpski (Srbija i Crna Gora (Bivša))', 'sr','srp','SRL', '2074', 'sr-Latn-CS');
INSERT INTO receiving_dock.language_codes VALUES('sr-Latn-ME', 'Serbian (Latin), (Montenegro)', 'srpski (Crna Gora)', 'sr','srp','SRP', '11290', 'sr-Latn-ME');
INSERT INTO receiving_dock.language_codes VALUES('sr-Latn-RS', 'Serbian (Latin), (Serbia)', 'srpski (Srbija)', 'sr','srp','SRM', '9242', 'sr-Latn-RS');
INSERT INTO receiving_dock.language_codes VALUES('st', 'Southern Sotho', 'Sesotho', 'st','sot','SOT', '48', 'st');
INSERT INTO receiving_dock.language_codes VALUES('st-ZA', 'Southern Sotho (South Africa)', 'Sesotho (South Africa)', 'st','sot','SOT', '1072', 'st-ZA');
INSERT INTO receiving_dock.language_codes VALUES('sv', 'Swedish', 'svenska', 'sv','swe','SVE', '29', 'sv');
INSERT INTO receiving_dock.language_codes VALUES('sv-FI', 'Swedish (Finland)', 'svenska (Finland)', 'sv','swe','SVF', '2077', 'sv-FI');
INSERT INTO receiving_dock.language_codes VALUES('sv-SE', 'Swedish (Sweden)', 'svenska (Sverige)', 'sv','swe','SVE', '1053', 'sv-SE');
INSERT INTO receiving_dock.language_codes VALUES('sw', 'Kiswahili', 'Kiswahili', 'sw','swa','SWK', '65', 'sw');
INSERT INTO receiving_dock.language_codes VALUES('sw-KE', 'Kiswahili (Kenya)', 'Kiswahili (Kenya)', 'sw','swa','SWK', '1089', 'sw-KE');
INSERT INTO receiving_dock.language_codes VALUES('syr', 'Syriac', 'ܣܘܪܝܝܐ', 'syr','syr','SYR', '90', 'syr');
INSERT INTO receiving_dock.language_codes VALUES('syr-SY', 'Syriac (Syria)', 'ܣܘܪܝܝܐ (ܣܘܪܝܐ)', 'syr','syr','SYR', '1114', 'syr-SY');
INSERT INTO receiving_dock.language_codes VALUES('ta', 'Tamil', 'தமிழ்', 'ta','tam','TAM', '73', 'ta');
INSERT INTO receiving_dock.language_codes VALUES('ta-IN', 'Tamil (India)', 'தமிழ் (இந்தியா)', 'ta','tam','TAM', '1097', 'ta-IN');
INSERT INTO receiving_dock.language_codes VALUES('ta-LK', 'Tamil (Sri Lanka)', 'தமிழ் (இலங்கை)', 'ta','tam','TAM', '2121', 'ta-LK');
INSERT INTO receiving_dock.language_codes VALUES('te', 'Telugu', 'తెలుగు', 'te','tel','TEL', '74', 'te');
INSERT INTO receiving_dock.language_codes VALUES('te-IN', 'Telugu (India)', 'తెలుగు (భారత దేశం)', 'te','tel','TEL', '1098', 'te-IN');
INSERT INTO receiving_dock.language_codes VALUES('tg', 'Tajik', 'Тоҷикӣ', 'tg','tgk','TAJ', '40', 'tg');
INSERT INTO receiving_dock.language_codes VALUES('tg-Cyrl', 'Tajik (Cyrillic)', 'Тоҷикӣ', 'tg','tgk','TAJ', '31784', 'tg-Cyrl');
INSERT INTO receiving_dock.language_codes VALUES('tg-Cyrl-TJ', 'Tajik (Cyrillic), (Tajikistan)', 'Тоҷикӣ (Тоҷикистон)', 'tg','tgk','TAJ', '1064', 'tg-Cyrl-TJ');
INSERT INTO receiving_dock.language_codes VALUES('th', 'Thai', 'ไทย', 'th','tha','THA', '30', 'th');
INSERT INTO receiving_dock.language_codes VALUES('th-TH', 'Thai (Thailand)', 'ไทย (ไทย)', 'th','tha','THA', '1054', 'th-TH');
INSERT INTO receiving_dock.language_codes VALUES('ti', 'Tigrinya', 'ትግርኛ', 'ti','tir','TIR', '115', 'ti');
INSERT INTO receiving_dock.language_codes VALUES('ti-ER', 'Tigrinya (Eritrea)', 'ትግርኛ (ኤርትራ)', 'ti','tir','TIR', '2163', 'ti-ER');
INSERT INTO receiving_dock.language_codes VALUES('ti-ET', 'Tigrinya (Ethiopia)', 'ትግርኛ (ኢትዮጵያ)', 'ti','tir','TIR', '1139', 'ti-ET');
INSERT INTO receiving_dock.language_codes VALUES('tk', 'Turkmen', 'Türkmen dili', 'tk','tuk','TUK', '66', 'tk');
INSERT INTO receiving_dock.language_codes VALUES('tk-TM', 'Turkmen (Turkmenistan)', 'Türkmen dili (Türkmenistan)', 'tk','tuk','TUK', '1090', 'tk-TM');
INSERT INTO receiving_dock.language_codes VALUES('tn', 'Setswana', 'Setswana', 'tn','tsn','TSN', '50', 'tn');
INSERT INTO receiving_dock.language_codes VALUES('tn-BW', 'Setswana (Botswana)', 'Setswana (Botswana)', 'tn','tsn','TSN', '2098', 'tn-BW');
INSERT INTO receiving_dock.language_codes VALUES('tn-ZA', 'Setswana (South Africa)', 'Setswana (Aforika Borwa)', 'tn','tsn','TSN', '1074', 'tn-ZA');
INSERT INTO receiving_dock.language_codes VALUES('tr', 'Turkish', 'Türkçe', 'tr','tur','TRK', '31', 'tr');
INSERT INTO receiving_dock.language_codes VALUES('tr-TR', 'Turkish (Turkey)', 'Türkçe (Türkiye)', 'tr','tur','TRK', '1055', 'tr-TR');
INSERT INTO receiving_dock.language_codes VALUES('ts', 'Tsonga', 'Xitsonga', 'ts','tso','TSO', '49', 'ts');
INSERT INTO receiving_dock.language_codes VALUES('ts-ZA', 'Tsonga (South Africa)', 'Xitsonga (South Africa)', 'ts','tso','TSO', '1073', 'ts-ZA');
INSERT INTO receiving_dock.language_codes VALUES('tt', 'Tatar', 'Татар', 'tt','tat','TTT', '68', 'tt');
INSERT INTO receiving_dock.language_codes VALUES('tt-RU', 'Tatar (Russia)', 'Татар (Россия)', 'tt','tat','TTT', '1092', 'tt-RU');
INSERT INTO receiving_dock.language_codes VALUES('tzm', 'Tamazight', 'Tamazight', 'tzm','tzm','TZM', '95', 'tzm');
INSERT INTO receiving_dock.language_codes VALUES('tzm-Latn', 'Central Atlas Tamazight (Latin)', 'Tamazight', 'tzm','tzm','TZM', '31839', 'tzm-Latn');
INSERT INTO receiving_dock.language_codes VALUES('tzm-Latn-DZ', 'Central Atlas Tamazight (Latin), (Algeria)', 'Tamazight (Djazaïr)', 'tzm','tzm','TZM', '2143', 'tzm-Latn-DZ');
INSERT INTO receiving_dock.language_codes VALUES('tzm-Tfng', 'Central Atlas Tamazight (Tifinagh)', 'ⵜⴰⵎⴰⵣⵉⵖⵜ', 'tzm','tzm','TZM', '30815', 'tzm-Tfng');
INSERT INTO receiving_dock.language_codes VALUES('tzm-Tfng-MA', 'Central Atlas Tamazight (Tifinagh), (Morocco)', 'ⵜⴰⵎⴰⵣⵉⵖⵜ (ⵍⵎⵖⵔⵉⴱ)', 'tzm','tzm','TZM', '4191', 'tzm-Tfng-MA');
INSERT INTO receiving_dock.language_codes VALUES('ug', 'Uyghur', 'ئۇيغۇرچە', 'ug','uig','UIG', '128', 'ug');
INSERT INTO receiving_dock.language_codes VALUES('ug-CN', 'Uyghur (China)', 'ئۇيغۇرچە (جۇڭخۇا خەلق جۇمھۇرىيىتى)', 'ug','uig','UIG', '1152', 'ug-CN');
INSERT INTO receiving_dock.language_codes VALUES('uk', 'Ukrainian', 'українська', 'uk','ukr','UKR', '34', 'uk');
INSERT INTO receiving_dock.language_codes VALUES('uk-UA', 'Ukrainian (Ukraine)', 'українська (Україна)', 'uk','ukr','UKR', '1058', 'uk-UA');
INSERT INTO receiving_dock.language_codes VALUES('ur', 'Urdu', 'اُردو', 'ur','urd','URD', '32', 'ur');
INSERT INTO receiving_dock.language_codes VALUES('ur-IN', 'Urdu (India)', 'اردو (بھارت)', 'ur','urd','URI', '2080', 'ur-IN');
INSERT INTO receiving_dock.language_codes VALUES('ur-PK', 'Urdu (Pakistan)', 'اُردو (پاکستان)', 'ur','urd','URD', '1056', 'ur-PK');
INSERT INTO receiving_dock.language_codes VALUES('uz', 'Uzbek', 'O''zbekcha', 'uz','uzb','UZB', '67', 'uz');
INSERT INTO receiving_dock.language_codes VALUES('uz-Cyrl', 'Uzbek (Cyrillic)', 'Ўзбекча', 'uz','uzb','UZB', '30787', 'uz-Cyrl');
INSERT INTO receiving_dock.language_codes VALUES('uz-Cyrl-UZ', 'Uzbek (Cyrillic), (Uzbekistan)', 'Ўзбекча (Ўзбекистон Республикаси)', 'uz','uzb','UZB', '2115', 'uz-Cyrl-UZ');
INSERT INTO receiving_dock.language_codes VALUES('uz-Latn', 'Uzbek (Latin)', 'O''zbekcha', 'uz','uzb','UZB', '31811', 'uz-Latn');
INSERT INTO receiving_dock.language_codes VALUES('uz-Latn-UZ', 'Uzbek (Latin), (Uzbekistan)', 'O''zbekcha (O''zbekiston Respublikasi)', 'uz','uzb','UZB', '1091', 'uz-Latn-UZ');
INSERT INTO receiving_dock.language_codes VALUES('vi', 'Vietnamese', 'Tiếng Việt', 'vi','vie','VIT', '42', 'vi');
INSERT INTO receiving_dock.language_codes VALUES('vi-VN', 'Vietnamese (Vietnam)', 'Tiếng Việt (Việt Nam)', 'vi','vie','VIT', '1066', 'vi-VN');
INSERT INTO receiving_dock.language_codes VALUES('wo', 'Wolof', 'Wolof', 'wo','wol','WOL', '136', 'wo');
INSERT INTO receiving_dock.language_codes VALUES('wo-SN', 'Wolof (Senegal)', 'Wolof (Senegaal)', 'wo','wol','WOL', '1160', 'wo-SN');
INSERT INTO receiving_dock.language_codes VALUES('xh', 'isiXhosa', 'isiXhosa', 'xh','xho','XHO', '52', 'xh');
INSERT INTO receiving_dock.language_codes VALUES('xh-ZA', 'isiXhosa (South Africa)', 'isiXhosa (uMzantsi Afrika)', 'xh','xho','XHO', '1076', 'xh-ZA');
INSERT INTO receiving_dock.language_codes VALUES('yo', 'Yoruba', 'Yoruba', 'yo','yor','YOR', '106', 'yo');
INSERT INTO receiving_dock.language_codes VALUES('yo-NG', 'Yoruba (Nigeria)', 'Yoruba (Nigeria)', 'yo','yor','YOR', '1130', 'yo-NG');
INSERT INTO receiving_dock.language_codes VALUES('zgh', 'Standard Morrocan Tamazight', 'Standard Morrocan Tamazight', 'zgh','zgh','ZHG', '4096', 'zgh');
INSERT INTO receiving_dock.language_codes VALUES('zgh-Tfng', 'Standard Morrocan Tamazight (Tifinagh)', 'ⵜⴰⵎⴰⵣⵉⵖⵜ', 'zgh','zgh','ZHG', '4096', 'zgh-Tfng');
INSERT INTO receiving_dock.language_codes VALUES('zgh-Tfng-MA', 'Standard Morrocan Tamazight (Tifinagh), (Morocco)', 'ⵜⴰⵎⴰⵣⵉⵖⵜ (ⵍⵎⵖⵔⵉⴱ)', 'zgh','zgh','ZHG', '4096', 'zgh-Tfng-MA');
INSERT INTO receiving_dock.language_codes VALUES('zh', 'Chinese', '中文', 'zh','zho','CHS', '30724', 'zh');
INSERT INTO receiving_dock.language_codes VALUES('zh-CHS', 'Chinese (Simplified) Legacy', '中文(简体) 旧版', 'zh','zho','CHS', '4', 'zh-Hans');
INSERT INTO receiving_dock.language_codes VALUES('zh-CHT', 'Chinese (Traditional) Legacy', '中文(繁體) 舊版', 'zh','zho','CHT', '31748', 'zh-Hant');
INSERT INTO receiving_dock.language_codes VALUES('zh-CN', 'Chinese (Simplified), (China)', '中文(中华人民共和国)', 'zh','zho','CHS', '2052', 'zh-CN');
INSERT INTO receiving_dock.language_codes VALUES('zh-HK', 'Chinese (Traditional), (Hong Kong SAR)', '中文(香港特別行政區)', 'zh','zho','ZHH', '3076', 'zh-HK');
INSERT INTO receiving_dock.language_codes VALUES('zh-Hans', 'Chinese (Simplified)', '中文(简体)', 'zh','zho','CHS', '4', 'zh-Hans');
INSERT INTO receiving_dock.language_codes VALUES('zh-Hant', 'Chinese (Traditional)', '中文(繁體)', 'zh','zho','CHT', '31748', 'zh-Hant');
INSERT INTO receiving_dock.language_codes VALUES('zh-MO', 'Chinese (Traditional), (Macao SAR)', '中文(澳門特別行政區)', 'zh','zho','ZHM', '5124', 'zh-MO');
INSERT INTO receiving_dock.language_codes VALUES('zh-SG', 'Chinese (Simplified), (Singapore)', '中文(新加坡)', 'zh','zho','ZHI', '4100', 'zh-SG');
INSERT INTO receiving_dock.language_codes VALUES('zh-TW', 'Chinese (Traditional), (Taiwan)', '中文(台灣)', 'zh','zho','CHT', '1028', 'zh-TW');
INSERT INTO receiving_dock.language_codes VALUES('zu', 'isiZulu', 'isiZulu', 'zu','zul','ZUL', '53', 'zu');
INSERT INTO receiving_dock.language_codes VALUES('zu-ZA', 'isiZulu (South Africa)', 'isiZulu (iNingizimu Afrika)', 'zu','zul','ZUL', '1077', 'zu-ZA');